#!/usr/bin/env python3
"""
Compile all .ui files to Python

Usage:
    python scripts/compile_ui.py
    python scripts/compile_ui.py --watch  # Watch for changes
"""
import os
import sys
# Ensure encoding is UTF-8 for subprocess outputs and file operations
os.environ["PYTHONIOENCODING"] = "utf-8"
import re
import subprocess
import time
from pathlib import Path
from datetime import datetime

UI_DIR = Path("ui")
OUTPUT_DIR = Path("src/ui")
RESOURCES_QRC = Path("assets/resources.qrc")
RESOURCES_OUTPUT = Path("src/ui/resources_rc.py")

# Mapping of promoted widget class names to their correct import paths
PROMOTED_WIDGET_IMPORTS = {
    # Widgets
    "HeaderAWidget": "from src.ui.widgets.header_a_widget import HeaderAWidget",
    "HeaderBWidget": "from src.ui.widgets.header_b_widget import HeaderBWidget",
    "HeaderMainWidget": "from src.ui.widgets.header_main_widget import HeaderMainWidget",
    "SidebarMenuWidget": "from src.ui.widgets.sidebar_menu_widget import SidebarMenuWidget",
    "DoorPanelHorizonWidget": "from src.ui.widgets.door_panel_horizon_widget import DoorPanelHorizonWidget",
    # Screens
    "Screen01Home": "from src.ui.screens.home import Screen01Home",
    "Screen31Login": "from src.ui.screens.login import Screen31Login",
    "Screen32User": "from src.ui.screens.user import Screen32User",
    "Screen33UserLists": "from src.ui.screens.user_lists import Screen33UserLists",
    "Screen34UserCreate": "from src.ui.screens.user_create import Screen34UserCreate",
    "Screen35UserEdit": "from src.ui.screens.user_edit import Screen35UserEdit",
}


def fix_promoted_widget_imports(content: str) -> str:
    """
    Fix promoted widget imports generated by pyside6-uic

    Args:
        content: Generated Python file content

    Returns:
        str: Content with corrected imports
    """
    # Pattern to match incorrect promoted widget imports
    # e.g., "from headerbwidget import HeaderBWidget"
    pattern = r'^from [\w.]+ import (\w+)$'

    lines = content.split('\n')
    new_lines = []
    seen_imports = set()

    for line in lines:
        match = re.match(pattern, line)
        if match:
            class_name = match.group(1)
            if class_name in PROMOTED_WIDGET_IMPORTS:
                replacement = PROMOTED_WIDGET_IMPORTS[class_name]
                if replacement not in seen_imports:
                    seen_imports.add(replacement)
                    new_lines.append(replacement)
                continue
        # Deduplicate any remaining import lines
        if (line.startswith('from ') or line.startswith('import ')) and line in seen_imports:
            continue
        new_lines.append(line)
        if line.startswith('from ') or line.startswith('import '):
            seen_imports.add(line)

    return '\n'.join(new_lines)


def compile_ui_file(ui_file: Path) -> bool:
    """
    Compile single .ui file to Python

    Args:
        ui_file: Path to .ui file

    Returns:
        bool: True if successful
    """
    # Calculate output path
    relative_path = ui_file.relative_to(UI_DIR)
    output_file = OUTPUT_DIR / relative_path.with_suffix('.py')
    output_file = output_file.with_name(f"{output_file.stem}_ui.py")

    # Create output directory
    output_file.parent.mkdir(parents=True, exist_ok=True)

    # Compile
    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"[{timestamp}] Compiling {ui_file} -> {output_file}")

    try:
        result = subprocess.run(
            ["pyside6-uic", str(ui_file), "-o", str(output_file)],
            capture_output=True,
            text=True,
            check=True
        )

        # Read generated file
        with open(output_file, 'r', encoding='utf-8') as f:
            content = f.read()

        # Fix resource imports
        content = content.replace(
            "import resources_rc\n",
            "from src.ui import resources_rc\n"
        )

        # Fix promoted widget imports
        content = fix_promoted_widget_imports(content)

        header = f"""# -*- coding: utf-8 -*-
# Auto-generated from {ui_file.name}
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

"""
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(header + content)

        print(f"  [OK] Success")
        return True

    except subprocess.CalledProcessError as e:
        print(f"  [ERR] Error: {e.stderr}")
        return False
    except Exception as e:
        print(f"  [ERR] Error: {e}")
        return False


def compile_resources() -> bool:
    """Compile Qt resource file (.qrc) to Python"""
    if not RESOURCES_QRC.exists():
        print(f"  [WARN] Resource file not found: {RESOURCES_QRC} (skipping)")
        return True

    timestamp = datetime.now().strftime("%H:%M:%S")
    print(f"[{timestamp}] Compiling {RESOURCES_QRC} -> {RESOURCES_OUTPUT}")

    # Ensure output directory exists
    RESOURCES_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    try:
        subprocess.run(
            ["pyside6-rcc", str(RESOURCES_QRC), "-o", str(RESOURCES_OUTPUT)],
            capture_output=True,
            text=True,
            check=True
        )
        print("  [OK] Success")
        return True
    except subprocess.CalledProcessError as e:
        print(f"  [ERR] Error: {e.stderr}")
        return False
    except Exception as e:
        print(f"  [ERR] Error: {e}")
        return False


def compile_all_ui_files():
    """Compile all .ui files in ui/ directory"""
    ui_files = list(UI_DIR.rglob("*.ui"))

    if not ui_files:
        print("No .ui files found in ui/ directory")
        return

    print("=" * 70)
    print(f"A9 HMI - UI Compiler")
    print(f"Compiling {len(ui_files)} .ui files")
    print("=" * 70)

    compile_resources()
    print()

    success_count = 0
    for ui_file in sorted(ui_files):
        if compile_ui_file(ui_file):
            success_count += 1
        print()

    print("=" * 70)
    print(f"Compilation complete: {success_count}/{len(ui_files)} successful")
    print("=" * 70)


def watch_and_compile():
    """Watch for .ui file changes and auto-compile"""
    print("=" * 70)
    print("A9 HMI - UI Compiler (Watch Mode)")
    print("Watching for .ui file changes... (Press Ctrl+C to stop)")
    print("=" * 70)
    print()

    # Track modification times
    file_mtimes = {}

    try:
        compile_resources()
        print()

        while True:
            ui_files = list(UI_DIR.rglob("*.ui"))

            for ui_file in ui_files:
                mtime = ui_file.stat().st_mtime

                if ui_file not in file_mtimes:
                    # First time seeing this file - compile it
                    file_mtimes[ui_file] = mtime
                    compile_ui_file(ui_file)
                    print()
                elif mtime > file_mtimes[ui_file]:
                    # File modified
                    print(f"\n{'='*70}")
                    print(f"Detected change in {ui_file}")
                    print('='*70)
                    compile_ui_file(ui_file)
                    file_mtimes[ui_file] = mtime
                    print()

            # Check for deleted files
            for tracked_file in list(file_mtimes.keys()):
                if not tracked_file.exists():
                    print(f"File deleted: {tracked_file}")
                    del file_mtimes[tracked_file]

            time.sleep(1)

    except KeyboardInterrupt:
        print("\n\nStopped watching")


def main():
    """Main entry point"""
    if len(sys.argv) > 1 and sys.argv[1] in ["--watch", "-w"]:
        watch_and_compile()
    else:
        compile_all_ui_files()


if __name__ == "__main__":
    main()
