# -*- coding: utf-8 -*-
# Auto-generated from home.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'home.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QLabel, QMainWindow,
    QSizePolicy, QSpacerItem, QToolButton, QVBoxLayout,
    QWidget)

from src.ui.widgets.door_panel_horizon_widget import DoorPanelHorizonWidget
from src.ui import resources_rc

class Ui_Screen01Home(object):
    def setupUi(self, Screen01Home):
        if not Screen01Home.objectName():
            Screen01Home.setObjectName(u"Screen01Home")
        Screen01Home.resize(884, 520)
        Screen01Home.setMinimumSize(QSize(884, 520))
        Screen01Home.setMaximumSize(QSize(884, 520))
        font = QFont()
        font.setFamilies([u"Poppins"])
        Screen01Home.setFont(font)
        Screen01Home.setStyleSheet(u"QMainWindow#Screen01Home {\n"
"    background-color: rgb(255, 255, 255);\n"
"    font-family: 'Poppins', 'Noto Sans Thai';\n"
"}\n"
"\n"
"/* Program selection cards */\n"
"QToolButton#obtn_program_1_standard,\n"
"QToolButton#obtn_program_2_short,\n"
"QToolButton#obtn_program_3_intensive,\n"
"QToolButton#obtn_program_4_rapid {\n"
"    background-color: white;\n"
"    border: 5px solid #003057;\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    font-family: \"Poppins\", \"Noto Sans Thai\";\n"
"    font-size: 20px;\n"
"    font-weight: bold;\n"
"    text-align: bottom;\n"
"    padding-top: 10px;\n"
"    padding-bottom: 20px;\n"
"}\n"
"QToolButton#obtn_program_1_standard:hover,\n"
"QToolButton#obtn_program_2_short:hover,\n"
"QToolButton#obtn_program_3_intensive:hover,\n"
"QToolButton#obtn_program_4_rapid:hover {\n"
"    background-color: #F0F4F8;\n"
"    border-color: #004B93;\n"
"}\n"
"\n"
"QToolButton#obtn_program_1_standard:pressed,\n"
"QToolButton#obtn_program_2_short:pressed,\n"
"QToolButton#obtn_prog"
                        "ram_3_intensive:pressed,\n"
"QToolButton#obtn_program_4_rapid:pressed {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"/* Navigation button (circular) */\n"
"QToolButton#obtn_next_program {\n"
"    background-color: #004B93;\n"
"    border: none;\n"
"    border-radius: 35px;\n"
"    color: white;\n"
"}\n"
"QToolButton#obtn_next_program:hover {\n"
"    background-color: #005BB0;\n"
"}\n"
"\n"
"QToolButton#obtn_next_program:pressed {\n"
"    background-color: #003A72;\n"
"}\n"
"\n"
"\n"
"QLabel#olbl_program {\n"
"    color: #003057;\n"
"    font-size: 56px;\n"
"    font-weight: bold;\n"
"    font-family: 'Poppins', 'Noto Sans Thai';\n"
"}\n"
"\n"
"QLabel#olbl_version {\n"
"    color: #000000;\n"
"    font-family: 'Poppins', 'Noto Sans Thai';\n"
"}\n"
"")
        self.centralwidget = QWidget(Screen01Home)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainContentLayout = QVBoxLayout()
        self.mainContentLayout.setObjectName(u"mainContentLayout")
        self.mainContentLayout.setContentsMargins(20, 0, 20, -1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.olbl_program = QLabel(self.centralwidget)
        self.olbl_program.setObjectName(u"olbl_program")
        self.olbl_program.setMinimumSize(QSize(0, 70))
        self.olbl_program.setMaximumSize(QSize(16777215, 70))
        self.olbl_program.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_2.addWidget(self.olbl_program)

        self.horizontalSpacer = QSpacerItem(70, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)


        self.mainContentLayout.addLayout(self.horizontalLayout_2)

        self.verticalSpacer_3 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.mainContentLayout.addItem(self.verticalSpacer_3)

        self.contentBodyLayout = QHBoxLayout()
        self.contentBodyLayout.setSpacing(0)
        self.contentBodyLayout.setObjectName(u"contentBodyLayout")
        self.buttons_layout = QHBoxLayout()
        self.buttons_layout.setSpacing(12)
        self.buttons_layout.setObjectName(u"buttons_layout")
        self.obtn_program_1_standard = QToolButton(self.centralwidget)
        self.obtn_program_1_standard.setObjectName(u"obtn_program_1_standard")
        self.obtn_program_1_standard.setMinimumSize(QSize(180, 250))
        self.obtn_program_1_standard.setMaximumSize(QSize(180, 250))
        icon = QIcon()
        icon.addFile(u":/images/time-management.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_program_1_standard.setIcon(icon)
        self.obtn_program_1_standard.setIconSize(QSize(100, 100))
        self.obtn_program_1_standard.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.buttons_layout.addWidget(self.obtn_program_1_standard)

        self.obtn_program_2_short = QToolButton(self.centralwidget)
        self.obtn_program_2_short.setObjectName(u"obtn_program_2_short")
        self.obtn_program_2_short.setMinimumSize(QSize(180, 250))
        self.obtn_program_2_short.setMaximumSize(QSize(180, 250))
        icon1 = QIcon()
        icon1.addFile(u":/images/time.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_program_2_short.setIcon(icon1)
        self.obtn_program_2_short.setIconSize(QSize(100, 100))
        self.obtn_program_2_short.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.buttons_layout.addWidget(self.obtn_program_2_short)

        self.obtn_program_3_intensive = QToolButton(self.centralwidget)
        self.obtn_program_3_intensive.setObjectName(u"obtn_program_3_intensive")
        self.obtn_program_3_intensive.setMinimumSize(QSize(180, 250))
        self.obtn_program_3_intensive.setMaximumSize(QSize(180, 250))
        icon2 = QIcon()
        icon2.addFile(u":/images/real-time.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_program_3_intensive.setIcon(icon2)
        self.obtn_program_3_intensive.setIconSize(QSize(100, 100))
        self.obtn_program_3_intensive.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.buttons_layout.addWidget(self.obtn_program_3_intensive)

        self.obtn_program_4_rapid = QToolButton(self.centralwidget)
        self.obtn_program_4_rapid.setObjectName(u"obtn_program_4_rapid")
        self.obtn_program_4_rapid.setMinimumSize(QSize(180, 250))
        self.obtn_program_4_rapid.setMaximumSize(QSize(180, 250))
        icon3 = QIcon()
        icon3.addFile(u":/images/stopwatch.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_program_4_rapid.setIcon(icon3)
        self.obtn_program_4_rapid.setIconSize(QSize(100, 100))
        self.obtn_program_4_rapid.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.buttons_layout.addWidget(self.obtn_program_4_rapid)

        self.obtn_next_program = QToolButton(self.centralwidget)
        self.obtn_next_program.setObjectName(u"obtn_next_program")
        self.obtn_next_program.setMinimumSize(QSize(70, 70))
        self.obtn_next_program.setMaximumSize(QSize(70, 70))
        icon4 = QIcon()
        icon4.addFile(u":/icon/chevron-right.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_next_program.setIcon(icon4)
        self.obtn_next_program.setIconSize(QSize(50, 50))

        self.buttons_layout.addWidget(self.obtn_next_program)


        self.contentBodyLayout.addLayout(self.buttons_layout)


        self.mainContentLayout.addLayout(self.contentBodyLayout)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.mainContentLayout.addItem(self.verticalSpacer_2)

        self.door_panel_horizon_widget = DoorPanelHorizonWidget(self.centralwidget)
        self.door_panel_horizon_widget.setObjectName(u"door_panel_horizon_widget")
        self.door_panel_horizon_widget.setMinimumSize(QSize(0, 100))
        self.door_panel_horizon_widget.setMaximumSize(QSize(16777215, 100))

        self.mainContentLayout.addWidget(self.door_panel_horizon_widget)

        self.olbl_version = QLabel(self.centralwidget)
        self.olbl_version.setObjectName(u"olbl_version")
        self.olbl_version.setMinimumSize(QSize(0, 20))
        self.olbl_version.setMaximumSize(QSize(16777215, 20))
        self.olbl_version.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.mainContentLayout.addWidget(self.olbl_version)


        self.horizontalLayout.addLayout(self.mainContentLayout)

        Screen01Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Screen01Home)

        QMetaObject.connectSlotsByName(Screen01Home)
    # setupUi

    def retranslateUi(self, Screen01Home):
        Screen01Home.setWindowTitle(QCoreApplication.translate("Screen01Home", u"Control Panel", None))
        self.olbl_program.setText(QCoreApplication.translate("Screen01Home", u"Program", None))
        self.obtn_program_1_standard.setText(QCoreApplication.translate("Screen01Home", u"xxxxxxxxxxxxx", None))
        self.obtn_program_2_short.setText(QCoreApplication.translate("Screen01Home", u"xxxxxxxxxxxxx", None))
        self.obtn_program_3_intensive.setText(QCoreApplication.translate("Screen01Home", u"xxxxxxxxxxxxx", None))
        self.obtn_program_4_rapid.setText(QCoreApplication.translate("Screen01Home", u"xxxxxxxxxxxxx", None))
        self.obtn_next_program.setText("")
        self.olbl_version.setText(QCoreApplication.translate("Screen01Home", u"V.1.0", None))
    # retranslateUi

