# -*- coding: utf-8 -*-
# Auto-generated from login.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'login.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QSpacerItem,
    QToolButton, QVBoxLayout, QWidget)

from src.ui.widgets.header_b_widget import HeaderBWidget
from src.ui import resources_rc

class Ui_Screen31Login(object):
    def setupUi(self, Screen31Login):
        if not Screen31Login.objectName():
            Screen31Login.setObjectName(u"Screen31Login")
        Screen31Login.resize(1024, 600)
        Screen31Login.setMinimumSize(QSize(1024, 600))
        Screen31Login.setMaximumSize(QSize(1024, 600))
        font = QFont()
        font.setFamilies([u"Poppins"])
        Screen31Login.setFont(font)
        Screen31Login.setStyleSheet(u"background-color: rgb(255, 255, 255);\n"
"font-family: 'Poppins', 'Noto Sans Thai';")
        self.centralwidget = QWidget(Screen31Login)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(20, 0, 20, 20)
        self.ofrm_header = HeaderBWidget(self.centralwidget)
        self.ofrm_header.setObjectName(u"ofrm_header")
        self.ofrm_header.setMinimumSize(QSize(0, 80))
        self.ofrm_header.setMaximumSize(QSize(16777215, 80))

        self.verticalLayout.addWidget(self.ofrm_header)

        self.mainContentLayout = QVBoxLayout()
        self.mainContentLayout.setSpacing(20)
        self.mainContentLayout.setObjectName(u"mainContentLayout")
        self.mainContentLayout.setContentsMargins(0, 0, 0, 0)
        self.loginFormLayout = QVBoxLayout()
        self.loginFormLayout.setSpacing(20)
        self.loginFormLayout.setObjectName(u"loginFormLayout")
        self.loginFormLayout.setContentsMargins(0, 20, 0, -1)
        self.oedit_username = QLineEdit(self.centralwidget)
        self.oedit_username.setObjectName(u"oedit_username")
        self.oedit_username.setMinimumSize(QSize(600, 60))
        self.oedit_username.setMaximumSize(QSize(600, 60))
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setPointSize(16)
        self.oedit_username.setFont(font1)
        self.oedit_username.setStyleSheet(u"QLineEdit {\n"
"	background-color: white;\n"
"	border: 5px solid #083459;\n"
"	border-radius: 30px;\n"
"	padding-left: 25px;\n"
"	padding-right: 25px;\n"
"	color: #000000;\n"
"}\n"
"QLineEdit:focus {\n"
"	border: 5px solid #0066CC;\n"
"}")

        self.loginFormLayout.addWidget(self.oedit_username, 0, Qt.AlignHCenter)

        self.ofrm_password_container = QFrame(self.centralwidget)
        self.ofrm_password_container.setObjectName(u"ofrm_password_container")
        self.ofrm_password_container.setMinimumSize(QSize(600, 60))
        self.ofrm_password_container.setMaximumSize(QSize(600, 60))
        self.ofrm_password_container.setStyleSheet(u"QFrame#ofrm_password_container {\n"
"	background-color: white;\n"
"	border: 5px solid #083459;\n"
"	border-radius: 30px;\n"
"}\n"
"QFrame#ofrm_password_container:focus-within {\n"
"	border: 5px solid #0066CC;\n"
"}")
        self.ofrm_password_container.setFrameShape(QFrame.NoFrame)
        self.passwordLayout = QHBoxLayout(self.ofrm_password_container)
        self.passwordLayout.setSpacing(0)
        self.passwordLayout.setObjectName(u"passwordLayout")
        self.passwordLayout.setContentsMargins(25, 0, 5, 0)
        self.oedit_password = QLineEdit(self.ofrm_password_container)
        self.oedit_password.setObjectName(u"oedit_password")
        self.oedit_password.setFont(font1)
        self.oedit_password.setStyleSheet(u"QLineEdit {\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	color: #000000;\n"
"}\n"
"QLineEdit:focus {\n"
"	border: none;\n"
"}")
        self.oedit_password.setEchoMode(QLineEdit.Password)

        self.passwordLayout.addWidget(self.oedit_password)

        self.obtn_password_toggle = QPushButton(self.ofrm_password_container)
        self.obtn_password_toggle.setObjectName(u"obtn_password_toggle")
        self.obtn_password_toggle.setMinimumSize(QSize(40, 40))
        self.obtn_password_toggle.setMaximumSize(QSize(40, 40))
        self.obtn_password_toggle.setStyleSheet(u"QPushButton {\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgba(0, 102, 204, 0.1);\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: rgba(0, 102, 204, 0.2);\n"
"}")
        icon = QIcon()
        icon.addFile(u":/images/password_hide.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_password_toggle.setIcon(icon)
        self.obtn_password_toggle.setIconSize(QSize(30, 30))
        self.obtn_password_toggle.setCheckable(True)

        self.passwordLayout.addWidget(self.obtn_password_toggle)


        self.loginFormLayout.addWidget(self.ofrm_password_container, 0, Qt.AlignHCenter)


        self.mainContentLayout.addLayout(self.loginFormLayout)

        self.loginButtonLayout = QHBoxLayout()
        self.loginButtonLayout.setObjectName(u"loginButtonLayout")
        self.horizontalSpacer_btnLeft = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.loginButtonLayout.addItem(self.horizontalSpacer_btnLeft)

        self.obtn_login = QPushButton(self.centralwidget)
        self.obtn_login.setObjectName(u"obtn_login")
        self.obtn_login.setMinimumSize(QSize(200, 70))
        self.obtn_login.setMaximumSize(QSize(200, 70))
        font2 = QFont()
        font2.setFamilies([u"Poppins"])
        font2.setPointSize(18)
        font2.setBold(True)
        self.obtn_login.setFont(font2)
        self.obtn_login.setStyleSheet(u"QPushButton {\n"
"	background-color: #27AE60;\n"
"	border: none;\n"
"	border-radius: 20px;\n"
"	color: white;\n"
"	padding: 10px 40px;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: #229954;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #1E8449;\n"
"}")

        self.loginButtonLayout.addWidget(self.obtn_login)

        self.horizontalSpacer_btnRight = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.loginButtonLayout.addItem(self.horizontalSpacer_btnRight)


        self.mainContentLayout.addLayout(self.loginButtonLayout)

        self.supervisorCardLayout = QHBoxLayout()
        self.supervisorCardLayout.setObjectName(u"supervisorCardLayout")
        self.horizontalSpacer_cardLeft = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.supervisorCardLayout.addItem(self.horizontalSpacer_cardLeft)

        self.obtn_card_id = QToolButton(self.centralwidget)
        self.obtn_card_id.setObjectName(u"obtn_card_id")
        self.obtn_card_id.setMinimumSize(QSize(160, 130))
        self.obtn_card_id.setMaximumSize(QSize(160, 130))
        font3 = QFont()
        font3.setFamilies([u"Poppins"])
        font3.setPointSize(14)
        font3.setBold(True)
        self.obtn_card_id.setFont(font3)
        self.obtn_card_id.setStyleSheet(u"QToolButton {\n"
"	background-color: white;\n"
"	border: 3px solid #003057;\n"
"	border-radius: 15px;\n"
"	color: #003057;\n"
"	padding: 10px;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u":/images/rfid.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_card_id.setIcon(icon1)
        self.obtn_card_id.setIconSize(QSize(120, 60))
        self.obtn_card_id.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)

        self.supervisorCardLayout.addWidget(self.obtn_card_id)

        self.horizontalSpacer_cardRight = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.supervisorCardLayout.addItem(self.horizontalSpacer_cardRight)


        self.mainContentLayout.addLayout(self.supervisorCardLayout)

        self.verticalSpacer_bottom = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.mainContentLayout.addItem(self.verticalSpacer_bottom)


        self.verticalLayout.addLayout(self.mainContentLayout)

        self.bottomLayout = QHBoxLayout()
        self.bottomLayout.setSpacing(0)
        self.bottomLayout.setObjectName(u"bottomLayout")
        self.bottomLayout.setContentsMargins(0, 0, 0, 0)
        self.obtn_previous = QPushButton(self.centralwidget)
        self.obtn_previous.setObjectName(u"obtn_previous")
        self.obtn_previous.setMinimumSize(QSize(70, 70))
        self.obtn_previous.setMaximumSize(QSize(70, 70))
        self.obtn_previous.setStyleSheet(u"QPushButton {\n"
"	background-color: #004B93;\n"
"	border-radius: 35px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #003057;\n"
"}")
        icon2 = QIcon()
        icon2.addFile(u":/icon/chevron-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_previous.setIcon(icon2)
        self.obtn_previous.setIconSize(QSize(55, 55))

        self.bottomLayout.addWidget(self.obtn_previous)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.bottomLayout.addItem(self.horizontalSpacer)


        self.verticalLayout.addLayout(self.bottomLayout)

        Screen31Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Screen31Login)

        QMetaObject.connectSlotsByName(Screen31Login)
    # setupUi

    def retranslateUi(self, Screen31Login):
        Screen31Login.setWindowTitle(QCoreApplication.translate("Screen31Login", u"Login", None))
        self.oedit_username.setPlaceholderText(QCoreApplication.translate("Screen31Login", u"\u0e1c\u0e39\u0e49\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19", None))
        self.oedit_password.setPlaceholderText(QCoreApplication.translate("Screen31Login", u"\u0e23\u0e2b\u0e31\u0e2a\u0e1c\u0e48\u0e32\u0e19", None))
        self.obtn_password_toggle.setText("")
        self.obtn_login.setText(QCoreApplication.translate("Screen31Login", u"\u0e22\u0e37\u0e19\u0e22\u0e31\u0e19", None))
        self.obtn_card_id.setText(QCoreApplication.translate("Screen31Login", u"Card ID", None))
        self.obtn_previous.setText("")
    # retranslateUi

