# -*- coding: utf-8 -*-
# Auto-generated from user_lists.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user_lists.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QHBoxLayout, QHeaderView,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QSpacerItem, QTableWidget, QTableWidgetItem, QVBoxLayout,
    QWidget)
from src.ui import resources_rc

class Ui_Screen33UserLists(object):
    def setupUi(self, Screen33UserLists):
        if not Screen33UserLists.objectName():
            Screen33UserLists.setObjectName(u"Screen33UserLists")
        Screen33UserLists.resize(884, 520)
        Screen33UserLists.setMinimumSize(QSize(884, 520))
        Screen33UserLists.setMaximumSize(QSize(884, 520))
        font = QFont()
        font.setFamilies([u"Poppins"])
        Screen33UserLists.setFont(font)
        Screen33UserLists.setStyleSheet(u"\n"
"        #ofrm_central { background-color: #ffffff; }\n"
"\n"
"        QLineEdit#otxt_search {\n"
"            background-color: #ffffff;\n"
"            border: 3px solid #003057;\n"
"            border-radius: 20px;\n"
"            padding: 6px 20px;\n"
"            font-family: 'Poppins', 'Noto Sans Thai';\n"
"            font-size: 16px;\n"
"            color: #333333;\n"
"        }\n"
"        QLineEdit#otxt_search:focus {\n"
"            border: 3px solid #0099cc;\n"
"        }\n"
"\n"
"        /* Delete button logic: turns red when active=\"true\" is set in Python code (row selected) */\n"
"        QPushButton#obtn_delete {\n"
"            background-color: #e0e0e0;\n"
"            border: none;\n"
"            border-radius: 15px;\n"
"            color: #333333;\n"
"            font-family: 'Poppins';\n"
"            font-weight: bold;\n"
"            font-size: 24px;\n"
"        }\n"
"        QPushButton#obtn_delete[active=\"true\"] {\n"
"            background-color: #E74C3C; /* Critical Red */\n"
""
                        "            color: #ffffff;\n"
"        }\n"
"        QPushButton#obtn_delete:hover {\n"
"            background-color: #eeeeee;\n"
"        }\n"
"        QPushButton#obtn_delete[active=\"true\"]:hover {\n"
"            background-color: #ff5252;\n"
"        }\n"
"        QPushButton#obtn_delete:pressed {\n"
"            background-color: #bdbdbd;\n"
"        }\n"
"        QPushButton#obtn_delete[active=\"true\"]:pressed {\n"
"            background-color: #c62828;\n"
"        }\n"
"        QPushButton#obtn_delete:disabled {\n"
"            background-color: #f5f5f5;\n"
"            color: #bdbdbd;\n"
"        }\n"
"\n"
"        QPushButton#obtn_add {\n"
"            background-color: #27AE60; /* Success Green */\n"
"            border: none;\n"
"            border-radius: 15px;\n"
"            color: #ffffff;\n"
"            font-family: 'Poppins';\n"
"            font-weight: bold;\n"
"            font-size: 24px;\n"
"        }\n"
"        QPushButton#obtn_add:hover {\n"
"            background-color: #2ECC7"
                        "1;\n"
"        }\n"
"        QPushButton#obtn_add:pressed {\n"
"            background-color: #1E8449;\n"
"        }\n"
"\n"
"        QPushButton#obtn_view {\n"
"            background-color: #e0e0e0;\n"
"            border: none;\n"
"            border-radius: 15px;\n"
"            color: #333333;\n"
"            font-family: 'Poppins', 'Noto Sans Thai';\n"
"            font-weight: bold;\n"
"            font-size: 16px;\n"
"        }\n"
"        QPushButton#obtn_view[active=\"true\"] {\n"
"            background-color: #003057;\n"
"            color: #ffffff;\n"
"        }\n"
"        QPushButton#obtn_view:hover {\n"
"            background-color: #eeeeee;\n"
"        }\n"
"        QPushButton#obtn_view[active=\"true\"]:hover {\n"
"            background-color: #004B93;\n"
"        }\n"
"        QPushButton#obtn_view:pressed {\n"
"            background-color: #bdbdbd;\n"
"        }\n"
"        QPushButton#obtn_view[active=\"true\"]:pressed {\n"
"            background-color: #002040;\n"
"        }\n"
"     "
                        "   QPushButton#obtn_view:disabled {\n"
"            background-color: #f5f5f5;\n"
"            color: #bdbdbd;\n"
"        }\n"
"\n"
"        QTableWidget#otbl_users {\n"
"            background-color: #ffffff;\n"
"            border: 2px solid #003057;\n"
"            border-radius: 10px;\n"
"            gridline-color: #dee2e6;\n"
"            font-family: 'Poppins', 'Noto Sans Thai';\n"
"            font-size: 14px;\n"
"            color: #333333;\n"
"        }\n"
"        QTableWidget#otbl_users::item {\n"
"            padding: 8px 12px;\n"
"            border-bottom: 1px solid #dee2e6;\n"
"        }\n"
"        QTableWidget#otbl_users::item:selected {\n"
"            background-color: #e3f2fd;\n"
"            color: #003057;\n"
"            outline: none;\n"
"            border: none;\n"
"        }\n"
"        QTableWidget#otbl_users::item:focus {\n"
"            outline: none;\n"
"            border: none;\n"
"        }\n"
"        QTableWidget#otbl_users QHeaderView::section {\n"
"            background"
                        "-color: #003057;\n"
"            color: #ffffff;\n"
"            font-family: 'Poppins', 'Noto Sans Thai';\n"
"            font-size: 14px;\n"
"            font-weight: bold;\n"
"            padding: 10px 12px;\n"
"            border: none;\n"
"            border-right: 1px solid #004B93;\n"
"        }\n"
"        QTableWidget#otbl_users QHeaderView::section:last {\n"
"            border-right: none;\n"
"        }\n"
"        QTableWidget#otbl_users QTableCornerButton::section {\n"
"            background-color: #003057;\n"
"            border: none;\n"
"        }\n"
"        QTableWidget#otbl_users QScrollBar:vertical {\n"
"            background: #f0f0f0;\n"
"            width: 10px;\n"
"            border-radius: 5px;\n"
"        }\n"
"        QTableWidget#otbl_users QScrollBar::handle:vertical {\n"
"            background: #003057;\n"
"            border-radius: 5px;\n"
"            min-height: 30px;\n"
"        }\n"
"        QTableWidget#otbl_users QScrollBar::add-line:vertical, \n"
"        QTableWidget#"
                        "otbl_users QScrollBar::sub-line:vertical {\n"
"            height: 0px;\n"
"        }\n"
"   ")
        self.ofrm_central = QWidget(Screen33UserLists)
        self.ofrm_central.setObjectName(u"ofrm_central")
        self.layout_main = QVBoxLayout(self.ofrm_central)
        self.layout_main.setSpacing(0)
        self.layout_main.setObjectName(u"layout_main")
        self.layout_main.setContentsMargins(20, 0, 20, 20)
        self.verticalSpacer = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.layout_main.addItem(self.verticalSpacer)

        self.layout_content = QVBoxLayout()
        self.layout_content.setSpacing(10)
        self.layout_content.setObjectName(u"layout_content")
        self.layout_content.setContentsMargins(0, 0, 0, 0)
        self.layout_toolbar = QHBoxLayout()
        self.layout_toolbar.setSpacing(15)
        self.layout_toolbar.setObjectName(u"layout_toolbar")
        self.otxt_search = QLineEdit(self.ofrm_central)
        self.otxt_search.setObjectName(u"otxt_search")
        self.otxt_search.setMinimumSize(QSize(0, 50))
        self.otxt_search.setMaximumSize(QSize(16777215, 50))
        self.otxt_search.setFont(font)
        self.otxt_search.setFocusPolicy(Qt.ClickFocus)

        self.layout_toolbar.addWidget(self.otxt_search)

        self.obtn_view = QPushButton(self.ofrm_central)
        self.obtn_view.setObjectName(u"obtn_view")
        self.obtn_view.setMinimumSize(QSize(120, 50))
        self.obtn_view.setMaximumSize(QSize(120, 50))
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setBold(True)
        self.obtn_view.setFont(font1)

        self.layout_toolbar.addWidget(self.obtn_view)

        self.obtn_delete = QPushButton(self.ofrm_central)
        self.obtn_delete.setObjectName(u"obtn_delete")
        self.obtn_delete.setMinimumSize(QSize(80, 50))
        self.obtn_delete.setMaximumSize(QSize(80, 50))
        self.obtn_delete.setFont(font1)

        self.layout_toolbar.addWidget(self.obtn_delete)

        self.obtn_add = QPushButton(self.ofrm_central)
        self.obtn_add.setObjectName(u"obtn_add")
        self.obtn_add.setMinimumSize(QSize(100, 50))
        self.obtn_add.setMaximumSize(QSize(100, 50))
        self.obtn_add.setFont(font1)

        self.layout_toolbar.addWidget(self.obtn_add)


        self.layout_content.addLayout(self.layout_toolbar)

        self.otbl_users = QTableWidget(self.ofrm_central)
        if (self.otbl_users.columnCount() < 5):
            self.otbl_users.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.otbl_users.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.otbl_users.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.otbl_users.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.otbl_users.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.otbl_users.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.otbl_users.setObjectName(u"otbl_users")
        self.otbl_users.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.otbl_users.setAlternatingRowColors(True)
        self.otbl_users.setSelectionMode(QAbstractItemView.SingleSelection)
        self.otbl_users.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.otbl_users.setShowGrid(True)
        self.otbl_users.setColumnCount(5)
        self.otbl_users.horizontalHeader().setDefaultSectionSize(150)
        self.otbl_users.horizontalHeader().setStretchLastSection(True)
        self.otbl_users.verticalHeader().setVisible(False)

        self.layout_content.addWidget(self.otbl_users)


        self.layout_main.addLayout(self.layout_content)

        Screen33UserLists.setCentralWidget(self.ofrm_central)

        self.retranslateUi(Screen33UserLists)

        QMetaObject.connectSlotsByName(Screen33UserLists)
    # setupUi

    def retranslateUi(self, Screen33UserLists):
        self.otxt_search.setPlaceholderText(QCoreApplication.translate("Screen33UserLists", u"\u0e04\u0e49\u0e19\u0e2b\u0e32", None))
        self.obtn_view.setText(QCoreApplication.translate("Screen33UserLists", u"\u0e14\u0e39\u0e02\u0e49\u0e2d\u0e21\u0e39\u0e25", None))
        self.obtn_delete.setText(QCoreApplication.translate("Screen33UserLists", u"-", None))
        self.obtn_add.setText(QCoreApplication.translate("Screen33UserLists", u"+", None))
        ___qtablewidgetitem = self.otbl_users.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Screen33UserLists", u"\u0e25\u0e33\u0e14\u0e31\u0e1a", None));
        ___qtablewidgetitem1 = self.otbl_users.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Screen33UserLists", u"\u0e0a\u0e37\u0e48\u0e2d - \u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25", None));
        ___qtablewidgetitem2 = self.otbl_users.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Screen33UserLists", u"\u0e1c\u0e39\u0e49\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19", None));
        ___qtablewidgetitem3 = self.otbl_users.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Screen33UserLists", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07", None));
        ___qtablewidgetitem4 = self.otbl_users.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Screen33UserLists", u"RFID", None));
        pass
    # retranslateUi

