# -*- coding: utf-8 -*-
# Auto-generated from user.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QSpacerItem,
    QVBoxLayout, QWidget)

from src.ui.widgets.header_b_widget import HeaderBWidget
from src.ui import resources_rc

class Ui_Screen32User(object):
    def setupUi(self, Screen32User):
        if not Screen32User.objectName():
            Screen32User.setObjectName(u"Screen32User")
        Screen32User.resize(1024, 600)
        Screen32User.setMinimumSize(QSize(1024, 600))
        Screen32User.setMaximumSize(QSize(1024, 600))
        font = QFont()
        font.setFamilies([u"Poppins"])
        Screen32User.setFont(font)
        Screen32User.setStyleSheet(u"\n"
"        #ofrm_central { background-color: #ffffff; }\n"
"   ")
        self.ofrm_central = QWidget(Screen32User)
        self.ofrm_central.setObjectName(u"ofrm_central")
        self.layout_main = QVBoxLayout(self.ofrm_central)
        self.layout_main.setSpacing(0)
        self.layout_main.setObjectName(u"layout_main")
        self.layout_main.setContentsMargins(20, 0, 20, 20)
        self.ofrm_header = HeaderBWidget(self.ofrm_central)
        self.ofrm_header.setObjectName(u"ofrm_header")
        self.ofrm_header.setMinimumSize(QSize(0, 80))
        self.ofrm_header.setMaximumSize(QSize(16777215, 80))

        self.layout_main.addWidget(self.ofrm_header)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.layout_main.addItem(self.verticalSpacer)

        self.layout_content = QVBoxLayout()
        self.layout_content.setSpacing(0)
        self.layout_content.setObjectName(u"layout_content")
        self.layout_content.setContentsMargins(0, 0, 0, 0)
        self.ofrm_user_card = QFrame(self.ofrm_central)
        self.ofrm_user_card.setObjectName(u"ofrm_user_card")
        self.ofrm_user_card.setMinimumSize(QSize(820, 380))
        self.ofrm_user_card.setMaximumSize(QSize(820, 380))
        self.ofrm_user_card.setStyleSheet(u"\n"
"            QFrame#ofrm_user_card {\n"
"                background-color: #ffffff;\n"
"                border: 4px solid #003057;\n"
"                border-radius: 30px;\n"
"            }\n"
"         ")
        self.ofrm_user_card.setFrameShape(QFrame.StyledPanel)
        self.layout_card = QVBoxLayout(self.ofrm_user_card)
        self.layout_card.setSpacing(10)
        self.layout_card.setObjectName(u"layout_card")
        self.layout_card.setContentsMargins(50, 20, 50, 20)
        self.layout_fullname_row = QHBoxLayout()
        self.layout_fullname_row.setSpacing(20)
        self.layout_fullname_row.setObjectName(u"layout_fullname_row")
        self.olbl_fullname_icon = QLabel(self.ofrm_user_card)
        self.olbl_fullname_icon.setObjectName(u"olbl_fullname_icon")
        self.olbl_fullname_icon.setMinimumSize(QSize(55, 55))
        self.olbl_fullname_icon.setMaximumSize(QSize(55, 55))
        self.olbl_fullname_icon.setStyleSheet(u"\n"
"                QLabel {\n"
"                    border: 3px solid #003057;\n"
"                    border-radius: 27px;\n"
"                    padding: 4px;\n"
"                }\n"
"              ")
        self.olbl_fullname_icon.setPixmap(QPixmap(u":/images/name.png"))
        self.olbl_fullname_icon.setScaledContents(True)
        self.olbl_fullname_icon.setAlignment(Qt.AlignCenter)

        self.layout_fullname_row.addWidget(self.olbl_fullname_icon)

        self.olbl_fullname_label = QLabel(self.ofrm_user_card)
        self.olbl_fullname_label.setObjectName(u"olbl_fullname_label")
        self.olbl_fullname_label.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: 900;")

        self.layout_fullname_row.addWidget(self.olbl_fullname_label)

        self.olbl_fullname_value = QLabel(self.ofrm_user_card)
        self.olbl_fullname_value.setObjectName(u"olbl_fullname_value")
        self.olbl_fullname_value.setStyleSheet(u"color: #00aa00; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: bold;")

        self.layout_fullname_row.addWidget(self.olbl_fullname_value)

        self.horizontalSpacer_fullname = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_fullname_row.addItem(self.horizontalSpacer_fullname)


        self.layout_card.addLayout(self.layout_fullname_row)

        self.layout_user_row = QHBoxLayout()
        self.layout_user_row.setSpacing(20)
        self.layout_user_row.setObjectName(u"layout_user_row")
        self.olbl_user_icon = QLabel(self.ofrm_user_card)
        self.olbl_user_icon.setObjectName(u"olbl_user_icon")
        self.olbl_user_icon.setMinimumSize(QSize(55, 55))
        self.olbl_user_icon.setMaximumSize(QSize(55, 55))
        self.olbl_user_icon.setStyleSheet(u"\n"
"                QLabel {\n"
"                    border: 3px solid #003057;\n"
"                    border-radius: 27px;\n"
"                    padding: 4px;\n"
"                }\n"
"              ")
        self.olbl_user_icon.setPixmap(QPixmap(u":/images/user.png"))
        self.olbl_user_icon.setScaledContents(True)
        self.olbl_user_icon.setAlignment(Qt.AlignCenter)

        self.layout_user_row.addWidget(self.olbl_user_icon)

        self.olbl_user_label = QLabel(self.ofrm_user_card)
        self.olbl_user_label.setObjectName(u"olbl_user_label")
        self.olbl_user_label.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: 900;")

        self.layout_user_row.addWidget(self.olbl_user_label)

        self.olbl_username_value = QLabel(self.ofrm_user_card)
        self.olbl_username_value.setObjectName(u"olbl_username_value")
        self.olbl_username_value.setStyleSheet(u"color: #00aa00; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: bold;")

        self.layout_user_row.addWidget(self.olbl_username_value)

        self.horizontalSpacer_user = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_user_row.addItem(self.horizontalSpacer_user)


        self.layout_card.addLayout(self.layout_user_row)

        self.layout_position_row = QHBoxLayout()
        self.layout_position_row.setSpacing(20)
        self.layout_position_row.setObjectName(u"layout_position_row")
        self.olbl_position_icon = QLabel(self.ofrm_user_card)
        self.olbl_position_icon.setObjectName(u"olbl_position_icon")
        self.olbl_position_icon.setMinimumSize(QSize(55, 55))
        self.olbl_position_icon.setMaximumSize(QSize(55, 55))
        self.olbl_position_icon.setStyleSheet(u"\n"
"                QLabel {\n"
"                    border: 3px solid #003057;\n"
"                    border-radius: 27px;\n"
"                    padding: 4px;\n"
"                }\n"
"              ")
        self.olbl_position_icon.setPixmap(QPixmap(u":/images/position.png"))
        self.olbl_position_icon.setScaledContents(True)
        self.olbl_position_icon.setAlignment(Qt.AlignCenter)

        self.layout_position_row.addWidget(self.olbl_position_icon)

        self.olbl_position_label = QLabel(self.ofrm_user_card)
        self.olbl_position_label.setObjectName(u"olbl_position_label")
        self.olbl_position_label.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: 900;")

        self.layout_position_row.addWidget(self.olbl_position_label)

        self.olbl_position_value = QLabel(self.ofrm_user_card)
        self.olbl_position_value.setObjectName(u"olbl_position_value")
        self.olbl_position_value.setStyleSheet(u"color: #00aa00; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: bold;")

        self.layout_position_row.addWidget(self.olbl_position_value)

        self.horizontalSpacer_position = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_position_row.addItem(self.horizontalSpacer_position)


        self.layout_card.addLayout(self.layout_position_row)

        self.layout_rfid_row = QHBoxLayout()
        self.layout_rfid_row.setSpacing(20)
        self.layout_rfid_row.setObjectName(u"layout_rfid_row")
        self.olbl_rfid_icon = QLabel(self.ofrm_user_card)
        self.olbl_rfid_icon.setObjectName(u"olbl_rfid_icon")
        self.olbl_rfid_icon.setMinimumSize(QSize(55, 55))
        self.olbl_rfid_icon.setMaximumSize(QSize(55, 55))
        self.olbl_rfid_icon.setStyleSheet(u"\n"
"               QLabel {\n"
"                   border: 3px solid #003057;\n"
"                   border-radius: 27px;\n"
"                   padding: 4px;\n"
"               }\n"
"              ")
        self.olbl_rfid_icon.setPixmap(QPixmap(u":/images/card_id.png"))
        self.olbl_rfid_icon.setScaledContents(True)
        self.olbl_rfid_icon.setAlignment(Qt.AlignCenter)

        self.layout_rfid_row.addWidget(self.olbl_rfid_icon)

        self.olbl_rfid_label = QLabel(self.ofrm_user_card)
        self.olbl_rfid_label.setObjectName(u"olbl_rfid_label")
        self.olbl_rfid_label.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: 900;")

        self.layout_rfid_row.addWidget(self.olbl_rfid_label)

        self.olbl_rfid_value = QLabel(self.ofrm_user_card)
        self.olbl_rfid_value.setObjectName(u"olbl_rfid_value")
        self.olbl_rfid_value.setStyleSheet(u"color: #00aa00; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: bold;")

        self.layout_rfid_row.addWidget(self.olbl_rfid_value)

        self.horizontalSpacer_rfid = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_rfid_row.addItem(self.horizontalSpacer_rfid)


        self.layout_card.addLayout(self.layout_rfid_row)

        self.layout_created_row = QHBoxLayout()
        self.layout_created_row.setSpacing(20)
        self.layout_created_row.setObjectName(u"layout_created_row")
        self.olbl_created_icon = QLabel(self.ofrm_user_card)
        self.olbl_created_icon.setObjectName(u"olbl_created_icon")
        self.olbl_created_icon.setMinimumSize(QSize(55, 55))
        self.olbl_created_icon.setMaximumSize(QSize(55, 55))
        self.olbl_created_icon.setStyleSheet(u"\n"
"                QLabel {\n"
"                    border: 3px solid #003057;\n"
"                    border-radius: 27px;\n"
"                    padding: 4px;\n"
"                }\n"
"              ")
        self.olbl_created_icon.setPixmap(QPixmap(u":/images/calendar.png"))
        self.olbl_created_icon.setScaledContents(True)
        self.olbl_created_icon.setAlignment(Qt.AlignCenter)

        self.layout_created_row.addWidget(self.olbl_created_icon)

        self.olbl_created_label = QLabel(self.ofrm_user_card)
        self.olbl_created_label.setObjectName(u"olbl_created_label")
        self.olbl_created_label.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: 900;")

        self.layout_created_row.addWidget(self.olbl_created_label)

        self.olbl_created_value = QLabel(self.ofrm_user_card)
        self.olbl_created_value.setObjectName(u"olbl_created_value")
        self.olbl_created_value.setStyleSheet(u"color: #00aa00; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 24px; font-weight: bold;")

        self.layout_created_row.addWidget(self.olbl_created_value)

        self.horizontalSpacer_created = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_created_row.addItem(self.horizontalSpacer_created)


        self.layout_card.addLayout(self.layout_created_row)


        self.layout_content.addWidget(self.ofrm_user_card, 0, Qt.AlignHCenter)


        self.layout_main.addLayout(self.layout_content)

        self.verticalSpacer_2 = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.layout_main.addItem(self.verticalSpacer_2)

        self.layout_bottom_bar = QHBoxLayout()
        self.layout_bottom_bar.setSpacing(20)
        self.layout_bottom_bar.setObjectName(u"layout_bottom_bar")
        self.layout_bottom_bar.setContentsMargins(0, -1, 0, -1)
        self.obtn_home = QPushButton(self.ofrm_central)
        self.obtn_home.setObjectName(u"obtn_home")
        self.obtn_home.setMinimumSize(QSize(70, 70))
        self.obtn_home.setMaximumSize(QSize(70, 70))
        self.obtn_home.setVisible(False)
        self.obtn_home.setStyleSheet(u"\n"
"               QPushButton { background-color: #004B93; border-radius: 35px; border: none; }\n"
"               QPushButton:pressed { background-color: #003057; }\n"
"           ")
        icon = QIcon()
        icon.addFile(u":/images/home.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_home.setIcon(icon)
        self.obtn_home.setIconSize(QSize(40, 40))

        self.layout_bottom_bar.addWidget(self.obtn_home)

        self.obtn_back = QPushButton(self.ofrm_central)
        self.obtn_back.setObjectName(u"obtn_back")
        self.obtn_back.setMinimumSize(QSize(70, 70))
        self.obtn_back.setMaximumSize(QSize(70, 70))
        self.obtn_back.setStyleSheet(u"\n"
"               QPushButton { background-color: #004B93; border-radius: 35px; border: none; }\n"
"               QPushButton:pressed { background-color: #003057; }\n"
"           ")
        icon1 = QIcon()
        icon1.addFile(u":/icon/chevron-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_back.setIcon(icon1)
        self.obtn_back.setIconSize(QSize(55, 55))

        self.layout_bottom_bar.addWidget(self.obtn_back)

        self.horizontalSpacer_left = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_bottom_bar.addItem(self.horizontalSpacer_left)

        self.obtn_edit = QPushButton(self.ofrm_central)
        self.obtn_edit.setObjectName(u"obtn_edit")
        self.obtn_edit.setMinimumSize(QSize(200, 50))
        self.obtn_edit.setMaximumSize(QSize(200, 50))
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setBold(True)
        self.obtn_edit.setFont(font1)
        self.obtn_edit.setStyleSheet(u"\n"
"               QPushButton {\n"
"                   background-color: #27AE60;\n"
"                   border: none;\n"
"                   border-radius: 15px;\n"
"                   color: #ffffff;\n"
"                   font-family: 'Poppins', 'Noto Sans Thai';\n"
"                   font-weight: bold;\n"
"                   font-size: 18px;\n"
"               }\n"
"               QPushButton:pressed { background-color: #1E8449; }\n"
"           ")

        self.layout_bottom_bar.addWidget(self.obtn_edit)

        self.horizontalSpacer_right = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_bottom_bar.addItem(self.horizontalSpacer_right)


        self.layout_main.addLayout(self.layout_bottom_bar)

        Screen32User.setCentralWidget(self.ofrm_central)

        self.retranslateUi(Screen32User)

        QMetaObject.connectSlotsByName(Screen32User)
    # setupUi

    def retranslateUi(self, Screen32User):
        self.olbl_fullname_icon.setText("")
        self.olbl_fullname_label.setText(QCoreApplication.translate("Screen32User", u"\u0e0a\u0e37\u0e48\u0e2d-\u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25 :", None))
        self.olbl_fullname_value.setText(QCoreApplication.translate("Screen32User", u"XXXXXXXXXXX", None))
        self.olbl_user_icon.setText("")
        self.olbl_user_label.setText(QCoreApplication.translate("Screen32User", u"\u0e1c\u0e39\u0e49\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19 :", None))
        self.olbl_username_value.setText(QCoreApplication.translate("Screen32User", u"XXXXXXXXXXX", None))
        self.olbl_position_icon.setText("")
        self.olbl_position_label.setText(QCoreApplication.translate("Screen32User", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07 :", None))
        self.olbl_position_value.setText(QCoreApplication.translate("Screen32User", u"XXXXXXXXXXX", None))
        self.olbl_rfid_icon.setText("")
        self.olbl_rfid_label.setText(QCoreApplication.translate("Screen32User", u"RFID :", None))
        self.olbl_rfid_value.setText(QCoreApplication.translate("Screen32User", u"XXXXXXXXXXX", None))
        self.olbl_created_icon.setText("")
        self.olbl_created_label.setText(QCoreApplication.translate("Screen32User", u"\u0e2a\u0e23\u0e49\u0e32\u0e07\u0e40\u0e21\u0e37\u0e48\u0e2d :", None))
        self.olbl_created_value.setText(QCoreApplication.translate("Screen32User", u"XXXXXXXXXXX", None))
        self.obtn_home.setText("")
        self.obtn_back.setText("")
        self.obtn_edit.setText(QCoreApplication.translate("Screen32User", u"\u0e41\u0e01\u0e49\u0e44\u0e02", None))
        pass
    # retranslateUi

