# -*- coding: utf-8 -*-
# Auto-generated from user_create.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user_create.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QMainWindow, QPushButton,
    QSizePolicy, QSpacerItem, QVBoxLayout, QWidget)

from src.ui.widgets.header_b_widget import HeaderBWidget
from src.ui import resources_rc

class Ui_Screen34UserCreate(object):
    def setupUi(self, Screen34UserCreate):
        if not Screen34UserCreate.objectName():
            Screen34UserCreate.setObjectName(u"Screen34UserCreate")
        Screen34UserCreate.resize(1024, 600)
        Screen34UserCreate.setMinimumSize(QSize(1024, 600))
        Screen34UserCreate.setMaximumSize(QSize(1024, 600))
        font = QFont()
        font.setFamilies([u"Poppins"])
        Screen34UserCreate.setFont(font)
        Screen34UserCreate.setStyleSheet(u"\n"
"        #ofrm_central { background-color: #ffffff; }\n"
"        /* Input fields */\n"
"        QLineEdit.formInput {\n"
"            background-color: #ffffff;\n"
"            border: 3px solid #003057;\n"
"            border-radius: 20px;\n"
"            padding: 8px 20px;\n"
"            font-family: \"Poppins\", \"Noto Sans Thai\";\n"
"            font-size: 16px;\n"
"            color: #333333;\n"
"        }\n"
"        QLineEdit.formInput:focus {\n"
"            border: 3px solid #0099cc;\n"
"        }\n"
"   ")
        self.ofrm_central = QWidget(Screen34UserCreate)
        self.ofrm_central.setObjectName(u"ofrm_central")
        self.layout_main = QVBoxLayout(self.ofrm_central)
        self.layout_main.setSpacing(0)
        self.layout_main.setObjectName(u"layout_main")
        self.layout_main.setContentsMargins(20, 0, 20, 0)
        self.ofrm_header = HeaderBWidget(self.ofrm_central)
        self.ofrm_header.setObjectName(u"ofrm_header")
        self.ofrm_header.setMinimumSize(QSize(0, 80))
        self.ofrm_header.setMaximumSize(QSize(16777215, 80))

        self.layout_main.addWidget(self.ofrm_header)

        self.layout_content = QVBoxLayout()
        self.layout_content.setSpacing(5)
        self.layout_content.setObjectName(u"layout_content")
        self.layout_content.setContentsMargins(0, 5, 0, 0)
        self.ofrm_form_card = QFrame(self.ofrm_central)
        self.ofrm_form_card.setObjectName(u"ofrm_form_card")
        self.ofrm_form_card.setMinimumSize(QSize(750, 400))
        self.ofrm_form_card.setMaximumSize(QSize(750, 400))
        self.ofrm_form_card.setStyleSheet(u"\n"
"            QFrame#ofrm_form_card {\n"
"                background-color: #ffffff;\n"
"                border: 4px solid #003057;\n"
"                border-radius: 30px;\n"
"            }\n"
"         ")
        self.ofrm_form_card.setFrameShape(QFrame.StyledPanel)
        self.layout_form = QVBoxLayout(self.ofrm_form_card)
        self.layout_form.setSpacing(12)
        self.layout_form.setObjectName(u"layout_form")
        self.layout_form.setContentsMargins(50, 25, 50, 25)
        self.layout_row_fullname = QHBoxLayout()
        self.layout_row_fullname.setObjectName(u"layout_row_fullname")
        self.olbl_fullname = QLabel(self.ofrm_form_card)
        self.olbl_fullname.setObjectName(u"olbl_fullname")
        self.olbl_fullname.setMinimumSize(QSize(160, 55))
        self.olbl_fullname.setMaximumSize(QSize(160, 55))
        self.olbl_fullname.setStyleSheet(u"color: #003057; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 15px; font-weight: bold;")
        self.olbl_fullname.setAlignment(Qt.AlignRight|Qt.AlignVCenter)

        self.layout_row_fullname.addWidget(self.olbl_fullname)

        self.otxt_fullname = QLineEdit(self.ofrm_form_card)
        self.otxt_fullname.setObjectName(u"otxt_fullname")
        self.otxt_fullname.setMinimumSize(QSize(0, 55))
        self.otxt_fullname.setMaximumSize(QSize(16777215, 55))
        self.otxt_fullname.setFont(font)

        self.layout_row_fullname.addWidget(self.otxt_fullname)


        self.layout_form.addLayout(self.layout_row_fullname)

        self.layout_row_username = QHBoxLayout()
        self.layout_row_username.setObjectName(u"layout_row_username")
        self.olbl_username = QLabel(self.ofrm_form_card)
        self.olbl_username.setObjectName(u"olbl_username")
        self.olbl_username.setMinimumSize(QSize(160, 55))
        self.olbl_username.setMaximumSize(QSize(160, 55))
        self.olbl_username.setStyleSheet(u"color: #003057; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 15px; font-weight: bold;")
        self.olbl_username.setAlignment(Qt.AlignRight|Qt.AlignVCenter)

        self.layout_row_username.addWidget(self.olbl_username)

        self.otxt_username = QLineEdit(self.ofrm_form_card)
        self.otxt_username.setObjectName(u"otxt_username")
        self.otxt_username.setMinimumSize(QSize(0, 55))
        self.otxt_username.setMaximumSize(QSize(16777215, 55))
        self.otxt_username.setFont(font)

        self.layout_row_username.addWidget(self.otxt_username)


        self.layout_form.addLayout(self.layout_row_username)

        self.layout_row_password = QHBoxLayout()
        self.layout_row_password.setObjectName(u"layout_row_password")
        self.olbl_password = QLabel(self.ofrm_form_card)
        self.olbl_password.setObjectName(u"olbl_password")
        self.olbl_password.setMinimumSize(QSize(160, 55))
        self.olbl_password.setMaximumSize(QSize(160, 55))
        self.olbl_password.setStyleSheet(u"color: #003057; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 15px; font-weight: bold;")
        self.olbl_password.setAlignment(Qt.AlignRight|Qt.AlignVCenter)

        self.layout_row_password.addWidget(self.olbl_password)

        self.otxt_password = QLineEdit(self.ofrm_form_card)
        self.otxt_password.setObjectName(u"otxt_password")
        self.otxt_password.setMinimumSize(QSize(0, 55))
        self.otxt_password.setMaximumSize(QSize(16777215, 55))
        self.otxt_password.setFont(font)
        self.otxt_password.setEchoMode(QLineEdit.Password)

        self.layout_row_password.addWidget(self.otxt_password)


        self.layout_form.addLayout(self.layout_row_password)

        self.layout_row_role = QHBoxLayout()
        self.layout_row_role.setObjectName(u"layout_row_role")
        self.olbl_role = QLabel(self.ofrm_form_card)
        self.olbl_role.setObjectName(u"olbl_role")
        self.olbl_role.setMinimumSize(QSize(160, 55))
        self.olbl_role.setMaximumSize(QSize(160, 55))
        self.olbl_role.setStyleSheet(u"color: #003057; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 15px; font-weight: bold;")
        self.olbl_role.setAlignment(Qt.AlignRight|Qt.AlignVCenter)

        self.layout_row_role.addWidget(self.olbl_role)

        self.ocmb_role = QComboBox(self.ofrm_form_card)
        self.ocmb_role.setObjectName(u"ocmb_role")
        self.ocmb_role.setMinimumSize(QSize(0, 55))
        self.ocmb_role.setMaximumSize(QSize(16777215, 55))
        self.ocmb_role.setFont(font)
        self.ocmb_role.setStyleSheet(u"\n"
"               QComboBox {\n"
"                   background-color: #ffffff;\n"
"                   border: 3px solid #003057;\n"
"                   border-radius: 20px;\n"
"                   padding: 8px 20px;\n"
"                   font-family: 'Poppins', 'Noto Sans Thai';\n"
"                   font-size: 16px;\n"
"                   color: #000000;\n"
"               }\n"
"               QComboBox:focus {\n"
"                   border: 3px solid #0099cc;\n"
"               }\n"
"               QComboBox::drop-down {\n"
"                   border: none;\n"
"                   width: 36px;\n"
"                }\n"
"               QComboBox::down-arrow {\n"
"                   image: url(:/images/arrow_down.png);\n"
"                   width: 20px;\n"
"                   height: 20px;\n"
"               }\n"
"               QComboBox QAbstractItemView {\n"
"                   background-color: #ffffff;\n"
"                   border: 3px solid #003057;\n"
"                   outline: none;\n"
"         "
                        "          selection-background-color: #e3f2fd;\n"
"                   selection-color: #000000;\n"
"                   color: #000000;\n"
"                   padding: 4px 0px;\n"
"               }\n"
"               QComboBox QAbstractItemView::item {\n"
"                   color: #000000;\n"
"                   padding: 10px 14px;\n"
"                   min-height: 34px;\n"
"                   border: none;\n"
"                   outline: none;\n"
"                   background-color: transparent;\n"
"               }\n"
"               QComboBox QAbstractItemView::item:selected {\n"
"                   background-color: #e3f2fd;\n"
"                   color: #000000;\n"
"                   border: none;\n"
"                   outline: none;\n"
"               }\n"
"               QComboBox QAbstractItemView::item:hover {\n"
"                   background-color: #e3f2fd;\n"
"                   color: #000000;\n"
"                   border: none;\n"
"                   outline: none;\n"
"               }\n"
" "
                        "              QComboBox QAbstractItemView::item:focus {\n"
"                   border: none;\n"
"                   outline: none;\n"
"               }\n"
"              ")

        self.layout_row_role.addWidget(self.ocmb_role)


        self.layout_form.addLayout(self.layout_row_role)

        self.layout_row_position = QHBoxLayout()
        self.layout_row_position.setObjectName(u"layout_row_position")
        self.olbl_position = QLabel(self.ofrm_form_card)
        self.olbl_position.setObjectName(u"olbl_position")
        self.olbl_position.setMinimumSize(QSize(160, 55))
        self.olbl_position.setMaximumSize(QSize(160, 55))
        self.olbl_position.setStyleSheet(u"color: #003057; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 15px; font-weight: bold;")
        self.olbl_position.setAlignment(Qt.AlignRight|Qt.AlignVCenter)

        self.layout_row_position.addWidget(self.olbl_position)

        self.otxt_position = QLineEdit(self.ofrm_form_card)
        self.otxt_position.setObjectName(u"otxt_position")
        self.otxt_position.setMinimumSize(QSize(0, 55))
        self.otxt_position.setMaximumSize(QSize(16777215, 55))
        self.otxt_position.setFont(font)

        self.layout_row_position.addWidget(self.otxt_position)


        self.layout_form.addLayout(self.layout_row_position)

        self.layout_row_rfid = QHBoxLayout()
        self.layout_row_rfid.setObjectName(u"layout_row_rfid")
        self.olbl_rfid = QLabel(self.ofrm_form_card)
        self.olbl_rfid.setObjectName(u"olbl_rfid")
        self.olbl_rfid.setMinimumSize(QSize(160, 55))
        self.olbl_rfid.setMaximumSize(QSize(160, 55))
        self.olbl_rfid.setStyleSheet(u"color: #003057; font-family: 'Poppins', 'Noto Sans Thai'; font-size: 15px; font-weight: bold;")
        self.olbl_rfid.setAlignment(Qt.AlignRight|Qt.AlignVCenter)

        self.layout_row_rfid.addWidget(self.olbl_rfid)

        self.layout_rfid = QHBoxLayout()
        self.layout_rfid.setSpacing(10)
        self.layout_rfid.setObjectName(u"layout_rfid")
        self.otxt_rfid = QLineEdit(self.ofrm_form_card)
        self.otxt_rfid.setObjectName(u"otxt_rfid")
        self.otxt_rfid.setMinimumSize(QSize(0, 55))
        self.otxt_rfid.setMaximumSize(QSize(16777215, 55))
        self.otxt_rfid.setFont(font)

        self.layout_rfid.addWidget(self.otxt_rfid)

        self.obtn_read_rfid = QPushButton(self.ofrm_form_card)
        self.obtn_read_rfid.setObjectName(u"obtn_read_rfid")
        self.obtn_read_rfid.setMinimumSize(QSize(120, 55))
        self.obtn_read_rfid.setMaximumSize(QSize(120, 55))
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setBold(True)
        self.obtn_read_rfid.setFont(font1)
        self.obtn_read_rfid.setStyleSheet(u"\n"
"                   QPushButton {\n"
"                       background-color: #3498DB;\n"
"                       border: none;\n"
"                       border-radius: 15px;\n"
"                       color: #ffffff;\n"
"                       font-family: 'Poppins', 'Noto Sans Thai';\n"
"                       font-weight: bold;\n"
"                       font-size: 14px;\n"
"                   }\n"
"                   QPushButton:pressed {\n"
"                       background-color: #2980B9;\n"
"                   }\n"
"                ")

        self.layout_rfid.addWidget(self.obtn_read_rfid)


        self.layout_row_rfid.addLayout(self.layout_rfid)


        self.layout_form.addLayout(self.layout_row_rfid)


        self.layout_content.addWidget(self.ofrm_form_card, 0, Qt.AlignHCenter)

        self.verticalSpacer_bottom = QSpacerItem(20, 0, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.layout_content.addItem(self.verticalSpacer_bottom)

        self.layout_bottom_bar = QHBoxLayout()
        self.layout_bottom_bar.setSpacing(20)
        self.layout_bottom_bar.setObjectName(u"layout_bottom_bar")
        self.layout_bottom_bar.setContentsMargins(0, -1, 0, -1)
        self.obtn_home = QPushButton(self.ofrm_central)
        self.obtn_home.setObjectName(u"obtn_home")
        self.obtn_home.setMinimumSize(QSize(70, 70))
        self.obtn_home.setMaximumSize(QSize(70, 70))
        self.obtn_home.setVisible(False)
        self.obtn_home.setStyleSheet(u"\n"
"              QPushButton {\n"
"                  background-color: #004B93;\n"
"                  border-radius: 35px;\n"
"                  border: none;\n"
"              }\n"
"              QPushButton:pressed {\n"
"                  background-color: #003057;\n"
"              }\n"
"           ")
        icon = QIcon()
        icon.addFile(u":/images/home.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_home.setIcon(icon)
        self.obtn_home.setIconSize(QSize(40, 40))

        self.layout_bottom_bar.addWidget(self.obtn_home)

        self.obtn_back = QPushButton(self.ofrm_central)
        self.obtn_back.setObjectName(u"obtn_back")
        self.obtn_back.setMinimumSize(QSize(70, 70))
        self.obtn_back.setMaximumSize(QSize(70, 70))
        self.obtn_back.setStyleSheet(u"\n"
"              QPushButton {\n"
"                  background-color: #004B93;\n"
"                  border-radius: 35px;\n"
"                  border: none;\n"
"              }\n"
"              QPushButton:pressed {\n"
"                  background-color: #003057;\n"
"              }\n"
"           ")
        icon1 = QIcon()
        icon1.addFile(u":/icon/chevron-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_back.setIcon(icon1)
        self.obtn_back.setIconSize(QSize(55, 55))

        self.layout_bottom_bar.addWidget(self.obtn_back)

        self.horizontalSpacer_left = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_bottom_bar.addItem(self.horizontalSpacer_left)

        self.obtn_cancel = QPushButton(self.ofrm_central)
        self.obtn_cancel.setObjectName(u"obtn_cancel")
        self.obtn_cancel.setMinimumSize(QSize(180, 50))
        self.obtn_cancel.setMaximumSize(QSize(180, 50))
        self.obtn_cancel.setFont(font1)
        self.obtn_cancel.setStyleSheet(u"\n"
"              QPushButton {\n"
"                  background-color: #e53935;\n"
"                  border: none;\n"
"                  border-radius: 15px;\n"
"                  color: #ffffff;\n"
"                  font-family: 'Poppins', 'Noto Sans Thai';\n"
"                  font-weight: bold;\n"
"                  font-size: 18px;\n"
"              }\n"
"              QPushButton:pressed {\n"
"                  background-color: #c62828;\n"
"              }\n"
"           ")

        self.layout_bottom_bar.addWidget(self.obtn_cancel)

        self.horizontalSpacer_mid = QSpacerItem(20, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.layout_bottom_bar.addItem(self.horizontalSpacer_mid)

        self.obtn_confirm = QPushButton(self.ofrm_central)
        self.obtn_confirm.setObjectName(u"obtn_confirm")
        self.obtn_confirm.setMinimumSize(QSize(180, 50))
        self.obtn_confirm.setMaximumSize(QSize(180, 50))
        self.obtn_confirm.setFont(font1)
        self.obtn_confirm.setStyleSheet(u"\n"
"              QPushButton {\n"
"                  background-color: #27AE60;\n"
"                  border: none;\n"
"                  border-radius: 15px;\n"
"                  color: #ffffff;\n"
"                  font-family: 'Poppins', 'Noto Sans Thai';\n"
"                  font-weight: bold;\n"
"                  font-size: 18px;\n"
"              }\n"
"              QPushButton:pressed {\n"
"                  background-color: #1E8449;\n"
"              }\n"
"           ")

        self.layout_bottom_bar.addWidget(self.obtn_confirm)

        self.horizontalSpacer_right = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_bottom_bar.addItem(self.horizontalSpacer_right)


        self.layout_content.addLayout(self.layout_bottom_bar)

        self.spacer_bottom_padding = QSpacerItem(20, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.layout_content.addItem(self.spacer_bottom_padding)


        self.layout_main.addLayout(self.layout_content)

        Screen34UserCreate.setCentralWidget(self.ofrm_central)

        self.retranslateUi(Screen34UserCreate)

        QMetaObject.connectSlotsByName(Screen34UserCreate)
    # setupUi

    def retranslateUi(self, Screen34UserCreate):
        self.olbl_fullname.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e0a\u0e37\u0e48\u0e2d - \u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25 :", None))
        self.otxt_fullname.setPlaceholderText(QCoreApplication.translate("Screen34UserCreate", u"\u0e0a\u0e37\u0e48\u0e2d - \u0e19\u0e32\u0e21\u0e2a\u0e01\u0e38\u0e25", None))
        self.otxt_fullname.setProperty(u"class", QCoreApplication.translate("Screen34UserCreate", u"formInput", None))
        self.olbl_username.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e1c\u0e39\u0e49\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19 :", None))
        self.otxt_username.setPlaceholderText(QCoreApplication.translate("Screen34UserCreate", u"\u0e1c\u0e39\u0e49\u0e43\u0e0a\u0e49\u0e07\u0e32\u0e19", None))
        self.otxt_username.setProperty(u"class", QCoreApplication.translate("Screen34UserCreate", u"formInput", None))
        self.olbl_password.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e23\u0e2b\u0e31\u0e2a\u0e1c\u0e48\u0e32\u0e19 :", None))
        self.otxt_password.setPlaceholderText(QCoreApplication.translate("Screen34UserCreate", u"\u0e23\u0e2b\u0e31\u0e2a\u0e1c\u0e48\u0e32\u0e19", None))
        self.otxt_password.setProperty(u"class", QCoreApplication.translate("Screen34UserCreate", u"formInput", None))
        self.olbl_role.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e1a\u0e17\u0e1a\u0e32\u0e17 :", None))
        self.olbl_position.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07 :", None))
        self.otxt_position.setPlaceholderText(QCoreApplication.translate("Screen34UserCreate", u"\u0e15\u0e33\u0e41\u0e2b\u0e19\u0e48\u0e07", None))
        self.otxt_position.setProperty(u"class", QCoreApplication.translate("Screen34UserCreate", u"formInput", None))
        self.olbl_rfid.setText(QCoreApplication.translate("Screen34UserCreate", u"RFID :", None))
        self.otxt_rfid.setPlaceholderText(QCoreApplication.translate("Screen34UserCreate", u"RFID", None))
        self.otxt_rfid.setProperty(u"class", QCoreApplication.translate("Screen34UserCreate", u"formInput", None))
        self.obtn_read_rfid.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e2d\u0e48\u0e32\u0e19 RFID", None))
        self.obtn_home.setText("")
        self.obtn_back.setText("")
        self.obtn_cancel.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
        self.obtn_confirm.setText(QCoreApplication.translate("Screen34UserCreate", u"\u0e22\u0e37\u0e19\u0e22\u0e31\u0e19", None))
        pass
    # retranslateUi

