# -*- coding: utf-8 -*-
# Auto-generated from bottom_setting_main_program.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bottom_setting_main_program.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QPushButton, QSizePolicy,
    QSpacerItem, QVBoxLayout, QWidget)
from src.ui import resources_rc

class Ui_BottomSettingMainProgram(object):
    def setupUi(self, BottomSettingMainProgram):
        if not BottomSettingMainProgram.objectName():
            BottomSettingMainProgram.setObjectName(u"BottomSettingMainProgram")
        BottomSettingMainProgram.resize(984, 50)
        BottomSettingMainProgram.setMinimumSize(QSize(984, 50))
        BottomSettingMainProgram.setMaximumSize(QSize(984, 50))
        BottomSettingMainProgram.setStyleSheet(u"\n"
"/* ===== RANGE TAB BUTTONS ===== */\n"
"QPushButton#obtn_range_1,\n"
"QPushButton#obtn_range_2,\n"
"QPushButton#obtn_range_3 {\n"
"    \n"
"    border-radius: 15px;\n"
"    font-family: 'Tahoma';\n"
"    font-weight: bold;\n"
"    font-size: 13pt;\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #000000;\n"
"    color: #000000;\n"
"}\n"
"/* Range tab: Active (selected) */\n"
"QPushButton#obtn_range_1[active=\"true\"],\n"
"QPushButton#obtn_range_2[active=\"true\"],\n"
"QPushButton#obtn_range_3[active=\"true\"] {\n"
"    background-color: #003057;\n"
"    border: 2px solid #003057;\n"
"    border-bottom: 3px solid #001a33;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"/* ===== PROGRAM LIST BUTTON ===== */\n"
"QPushButton#obtn_program_list {\n"
"    border-radius: 15px;\n"
"    font-family: 'Poppins', 'Noto Sans Thai';\n"
"    font-weight: bold;\n"
"    font-size: 13pt;\n"
"    background-color: #003057;\n"
"    border: none;\n"
"    color: #ffffff;\n"
"}\n"
"QPushButton#obtn_program_list:pressed {\n"
""
                        "    background-color: #194c7a;\n"
"}\n"
"\n"
"/* ===== ACTION LEFT BUTTON (\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01 / \u0e40\u0e14\u0e23\u0e19 / \u0e25\u0e49\u0e32\u0e07) ===== */\n"
"/* Default: \u0e22\u0e01\u0e40\u0e25\u0e34\u0e01 \u2014 Red */\n"
"QPushButton#obtn_action_left {\n"
"    \n"
"    border-radius: 15px;\n"
"    font-family: 'Tahoma', 'Noto Sans Thai';\n"
"    font-weight: bold;\n"
"    font-size: 13pt;\n"
"    border: none;\n"
"    color: #ffffff;\n"
"    background-color: #FF0000;\n"
"}\n"
"QPushButton#obtn_action_left:pressed {\n"
"    background-color: #CC0000;\n"
"}\n"
"/* mode_set_wash: \u0e40\u0e14\u0e23\u0e19 \u2014 Orange */\n"
"QPushButton#obtn_action_left[mode=\"set_wash\"] {\n"
"    background-color: #FF8C00;\n"
"}\n"
"QPushButton#obtn_action_left[mode=\"set_wash\"]:pressed {\n"
"    background-color: #E67E00;\n"
"}\n"
"/* mode_set_drain: \u0e25\u0e49\u0e32\u0e07 \u2014 Cyan */\n"
"QPushButton#obtn_action_left[mode=\"set_drain\"] {\n"
"    background-color: #00BCD4;\n"
"}\n"
"QPushButton#"
                        "obtn_action_left[mode=\"set_drain\"]:pressed {\n"
"    background-color: #0097A7;\n"
"}\n"
"\n"
"/* ===== ACTION RIGHT BUTTON (\u0e22\u0e37\u0e19\u0e22\u0e31\u0e19 / \u0e1a\u0e31\u0e19\u0e17\u0e36\u0e01) ===== */\n"
"QPushButton#obtn_action_right {\n"
"    \n"
"    border-radius: 15px;\n"
"    font-family: 'Tahoma', 'Noto Sans Thai';\n"
"    font-weight: bold;\n"
"    font-size: 13pt;\n"
"    border: none;\n"
"    color: #ffffff;\n"
"    background-color: #27AE60;\n"
"}\n"
"QPushButton#obtn_action_right:pressed {\n"
"    background-color: #1E8449;\n"
"}\n"
"   ")
        self.layout_main = QVBoxLayout(BottomSettingMainProgram)
        self.layout_main.setObjectName(u"layout_main")
        self.layout_main.setContentsMargins(0, 0, 0, 0)
        self.layout_bottom = QHBoxLayout()
        self.layout_bottom.setSpacing(10)
        self.layout_bottom.setObjectName(u"layout_bottom")
        self.obtn_range_1 = QPushButton(BottomSettingMainProgram)
        self.obtn_range_1.setObjectName(u"obtn_range_1")
        self.obtn_range_1.setMinimumSize(QSize(152, 50))
        self.obtn_range_1.setMaximumSize(QSize(152, 50))

        self.layout_bottom.addWidget(self.obtn_range_1)

        self.obtn_range_2 = QPushButton(BottomSettingMainProgram)
        self.obtn_range_2.setObjectName(u"obtn_range_2")
        self.obtn_range_2.setMinimumSize(QSize(152, 50))
        self.obtn_range_2.setMaximumSize(QSize(152, 50))

        self.layout_bottom.addWidget(self.obtn_range_2)

        self.obtn_range_3 = QPushButton(BottomSettingMainProgram)
        self.obtn_range_3.setObjectName(u"obtn_range_3")
        self.obtn_range_3.setMinimumSize(QSize(152, 50))
        self.obtn_range_3.setMaximumSize(QSize(152, 50))

        self.layout_bottom.addWidget(self.obtn_range_3)

        self.spacer_horizontal = QSpacerItem(0, 0, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layout_bottom.addItem(self.spacer_horizontal)

        self.obtn_program_list = QPushButton(BottomSettingMainProgram)
        self.obtn_program_list.setObjectName(u"obtn_program_list")
        self.obtn_program_list.setMinimumSize(QSize(172, 50))
        self.obtn_program_list.setMaximumSize(QSize(172, 50))
        icon = QIcon()
        icon.addFile(u":/images/document.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_program_list.setIcon(icon)
        self.obtn_program_list.setIconSize(QSize(28, 28))

        self.layout_bottom.addWidget(self.obtn_program_list)

        self.obtn_action_left = QPushButton(BottomSettingMainProgram)
        self.obtn_action_left.setObjectName(u"obtn_action_left")
        self.obtn_action_left.setMinimumSize(QSize(150, 50))
        self.obtn_action_left.setMaximumSize(QSize(150, 50))

        self.layout_bottom.addWidget(self.obtn_action_left)

        self.obtn_action_right = QPushButton(BottomSettingMainProgram)
        self.obtn_action_right.setObjectName(u"obtn_action_right")
        self.obtn_action_right.setMinimumSize(QSize(150, 50))
        self.obtn_action_right.setMaximumSize(QSize(150, 50))

        self.layout_bottom.addWidget(self.obtn_action_right)


        self.layout_main.addLayout(self.layout_bottom)


        self.retranslateUi(BottomSettingMainProgram)

        QMetaObject.connectSlotsByName(BottomSettingMainProgram)
    # setupUi

    def retranslateUi(self, BottomSettingMainProgram):
        self.obtn_range_1.setText(QCoreApplication.translate("BottomSettingMainProgram", u"1-8", None))
        self.obtn_range_2.setText(QCoreApplication.translate("BottomSettingMainProgram", u"9-16", None))
        self.obtn_range_3.setText(QCoreApplication.translate("BottomSettingMainProgram", u"17-24", None))
        self.obtn_program_list.setText(QCoreApplication.translate("BottomSettingMainProgram", u"\u0e42\u0e1b\u0e23\u0e41\u0e01\u0e23\u0e21", None))
        self.obtn_action_left.setText(QCoreApplication.translate("BottomSettingMainProgram", u"\u0e22\u0e01\u0e40\u0e25\u0e34\u0e01", None))
        self.obtn_action_right.setText(QCoreApplication.translate("BottomSettingMainProgram", u"\u0e22\u0e37\u0e19\u0e22\u0e31\u0e19", None))
        pass
    # retranslateUi

