# -*- coding: utf-8 -*-
# Auto-generated from bottom_nav_auto_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bottom_nav_auto_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QPushButton, QSizePolicy,
    QWidget)

class Ui_BottomNavAutoWidget(object):
    def setupUi(self, BottomNavAutoWidget):
        if not BottomNavAutoWidget.objectName():
            BottomNavAutoWidget.setObjectName(u"BottomNavAutoWidget")
        BottomNavAutoWidget.resize(984, 70)
        BottomNavAutoWidget.setMinimumSize(QSize(0, 70))
        BottomNavAutoWidget.setMaximumSize(QSize(16777215, 70))
        BottomNavAutoWidget.setStyleSheet(u"font-family: 'Poppins', 'Noto Sans Thai';")
        self.mainLayout = QHBoxLayout(BottomNavAutoWidget)
        self.mainLayout.setSpacing(20)
        self.mainLayout.setObjectName(u"mainLayout")
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.obtn_button1 = QPushButton(BottomNavAutoWidget)
        self.obtn_button1.setObjectName(u"obtn_button1")
        self.obtn_button1.setMinimumSize(QSize(230, 50))
        self.obtn_button1.setMaximumSize(QSize(230, 50))
        font = QFont()
        font.setFamilies([u"Noto Sans Thai"])
        font.setPointSize(14)
        font.setBold(True)
        self.obtn_button1.setFont(font)
        self.obtn_button1.setStyleSheet(u"QPushButton {\n"
"	background-color: white;\n"
"	border: none;\n"
"	border-radius: 10px;\n"
"	color: #003057;\n"
"	font-family: 'Noto Sans Thai';\n"
"	font-weight: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #E3F2FD;\n"
"}")

        self.mainLayout.addWidget(self.obtn_button1)

        self.obtn_button2 = QPushButton(BottomNavAutoWidget)
        self.obtn_button2.setObjectName(u"obtn_button2")
        self.obtn_button2.setMinimumSize(QSize(230, 50))
        self.obtn_button2.setMaximumSize(QSize(230, 50))
        self.obtn_button2.setFont(font)
        self.obtn_button2.setStyleSheet(u"QPushButton {\n"
"	background-color: white;\n"
"	border: none;\n"
"	border-radius: 10px;\n"
"	color: #003057;\n"
"	font-family: 'Noto Sans Thai';\n"
"	font-weight: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #E3F2FD;\n"
"}")

        self.mainLayout.addWidget(self.obtn_button2)

        self.obtn_button3 = QPushButton(BottomNavAutoWidget)
        self.obtn_button3.setObjectName(u"obtn_button3")
        self.obtn_button3.setMinimumSize(QSize(230, 50))
        self.obtn_button3.setMaximumSize(QSize(230, 50))
        self.obtn_button3.setFont(font)
        self.obtn_button3.setStyleSheet(u"QPushButton {\n"
"	background-color: #F59E0B;\n"
"	border: none;\n"
"	border-radius: 10px;\n"
"	color: white;\n"
"	font-family: 'Noto Sans Thai';\n"
"	font-weight: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #D97706;\n"
"}")

        self.mainLayout.addWidget(self.obtn_button3)

        self.obtn_button4 = QPushButton(BottomNavAutoWidget)
        self.obtn_button4.setObjectName(u"obtn_button4")
        self.obtn_button4.setMinimumSize(QSize(230, 50))
        self.obtn_button4.setMaximumSize(QSize(230, 50))
        self.obtn_button4.setFont(font)
        self.obtn_button4.setStyleSheet(u"QPushButton {\n"
"	background-color: #EF4444;\n"
"	border: none;\n"
"	border-radius: 10px;\n"
"	color: white;\n"
"	font-family: 'Noto Sans Thai';\n"
"	font-weight: bold;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #DC2626;\n"
"}")

        self.mainLayout.addWidget(self.obtn_button4)


        self.retranslateUi(BottomNavAutoWidget)

        QMetaObject.connectSlotsByName(BottomNavAutoWidget)
    # setupUi

    def retranslateUi(self, BottomNavAutoWidget):
        BottomNavAutoWidget.setWindowTitle(QCoreApplication.translate("BottomNavAutoWidget", u"Bottom Navigation Auto Widget", None))
        self.obtn_button1.setText(QCoreApplication.translate("BottomNavAutoWidget", u"Button 1", None))
        self.obtn_button2.setText(QCoreApplication.translate("BottomNavAutoWidget", u"Button 2", None))
        self.obtn_button3.setText(QCoreApplication.translate("BottomNavAutoWidget", u"Skip", None))
        self.obtn_button4.setText(QCoreApplication.translate("BottomNavAutoWidget", u"Cancel", None))
    # retranslateUi

