# -*- coding: utf-8 -*-
# Auto-generated from bottom_nav_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bottom_nav_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QPushButton, QSizePolicy,
    QSpacerItem, QWidget)
from src.ui import resources_rc

class Ui_BottomNavWidget(object):
    def setupUi(self, BottomNavWidget):
        if not BottomNavWidget.objectName():
            BottomNavWidget.setObjectName(u"BottomNavWidget")
        BottomNavWidget.resize(984, 70)
        BottomNavWidget.setMinimumSize(QSize(0, 70))
        BottomNavWidget.setMaximumSize(QSize(16777215, 70))
        font = QFont()
        font.setFamilies([u"Poppins"])
        BottomNavWidget.setFont(font)
        BottomNavWidget.setStyleSheet(u"#BottomNavWidget { \n"
"    background-color: transparent;\n"
"    font-family: 'Poppins', 'Noto Sans Thai';\n"
"}")
        self.bottomNavLayout = QHBoxLayout(BottomNavWidget)
        self.bottomNavLayout.setSpacing(20)
        self.bottomNavLayout.setObjectName(u"bottomNavLayout")
        self.bottomNavLayout.setContentsMargins(0, 0, 0, 0)
        self.obtn_home = QPushButton(BottomNavWidget)
        self.obtn_home.setObjectName(u"obtn_home")
        self.obtn_home.setMinimumSize(QSize(70, 70))
        self.obtn_home.setMaximumSize(QSize(70, 70))
        self.obtn_home.setStyleSheet(u"QPushButton {\n"
"	background-color: #004B93;\n"
"	border-radius: 35px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #003057;\n"
"}")
        icon = QIcon()
        icon.addFile(u":/icon/chevron-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_home.setIcon(icon)
        self.obtn_home.setIconSize(QSize(50, 50))

        self.bottomNavLayout.addWidget(self.obtn_home)

        self.horizontalSpacer_left = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.bottomNavLayout.addItem(self.horizontalSpacer_left)

        self.obtn_previous = QPushButton(BottomNavWidget)
        self.obtn_previous.setObjectName(u"obtn_previous")
        self.obtn_previous.setMinimumSize(QSize(70, 70))
        self.obtn_previous.setMaximumSize(QSize(70, 70))
        self.obtn_previous.setStyleSheet(u"QPushButton {\n"
"	background-color: #004B93;\n"
"	border-radius: 35px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #003057;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u":/icon/arrow-left.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_previous.setIcon(icon1)
        self.obtn_previous.setIconSize(QSize(40, 40))

        self.bottomNavLayout.addWidget(self.obtn_previous)

        self.obtn_next = QPushButton(BottomNavWidget)
        self.obtn_next.setObjectName(u"obtn_next")
        self.obtn_next.setMinimumSize(QSize(70, 70))
        self.obtn_next.setMaximumSize(QSize(70, 70))
        self.obtn_next.setStyleSheet(u"QPushButton {\n"
"	background-color: #004B93;\n"
"	border-radius: 35px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #003057;\n"
"}")
        icon2 = QIcon()
        icon2.addFile(u":/icon/arrow-right.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_next.setIcon(icon2)
        self.obtn_next.setIconSize(QSize(40, 40))

        self.bottomNavLayout.addWidget(self.obtn_next)


        self.retranslateUi(BottomNavWidget)

        QMetaObject.connectSlotsByName(BottomNavWidget)
    # setupUi

    def retranslateUi(self, BottomNavWidget):
        self.obtn_home.setText("")
        self.obtn_previous.setText("")
        self.obtn_next.setText("")
        pass
    # retranslateUi

