# -*- coding: utf-8 -*-
# Auto-generated from door_panel_horizon_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'door_panel_horizon_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QPushButton, QSizePolicy,
    QSpacerItem, QWidget)
from src.ui import resources_rc

class Ui_DoorPanelHorizonWidget(object):
    def setupUi(self, DoorPanelHorizonWidget):
        if not DoorPanelHorizonWidget.objectName():
            DoorPanelHorizonWidget.setObjectName(u"DoorPanelHorizonWidget")
        DoorPanelHorizonWidget.resize(400, 100)
        DoorPanelHorizonWidget.setMinimumSize(QSize(400, 100))
        DoorPanelHorizonWidget.setMaximumSize(QSize(400, 100))
        DoorPanelHorizonWidget.setStyleSheet(u"QWidget#DoorPanelHorizonWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Door buttons (square gray) */\n"
"#obtn_door_open,\n"
"#obtn_door_close {\n"
"    background-color: #D9D9D9;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"#obtn_door_open:hover,\n"
"#obtn_door_close:hover {\n"
"    background-color: #E5E5E5;\n"
"}\n"
"\n"
"#obtn_door_open:pressed,\n"
"#obtn_door_close:pressed {\n"
"    background-color: #FFA93F;\n"
"}\n"
"* {\n"
"    font-family: 'Poppins', 'Noto Sans Thai';\n"
"}\n"
"")
        self.doorPanelHorizonLayout = QHBoxLayout(DoorPanelHorizonWidget)
        self.doorPanelHorizonLayout.setSpacing(0)
        self.doorPanelHorizonLayout.setObjectName(u"doorPanelHorizonLayout")
        self.doorPanelHorizonLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(40, -1, 40, -1)
        self.obtn_door_open = QPushButton(DoorPanelHorizonWidget)
        self.obtn_door_open.setObjectName(u"obtn_door_open")
        self.obtn_door_open.setMinimumSize(QSize(100, 100))
        self.obtn_door_open.setMaximumSize(QSize(100, 100))
        icon = QIcon()
        icon.addFile(u":/icon/door-slide-run-open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_door_open.setIcon(icon)
        self.obtn_door_open.setIconSize(QSize(65, 65))
        self.obtn_door_open.setAutoDefault(False)
        self.obtn_door_open.setFlat(False)

        self.horizontalLayout.addWidget(self.obtn_door_open)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.obtn_door_close = QPushButton(DoorPanelHorizonWidget)
        self.obtn_door_close.setObjectName(u"obtn_door_close")
        self.obtn_door_close.setMinimumSize(QSize(100, 100))
        self.obtn_door_close.setMaximumSize(QSize(100, 100))
        icon1 = QIcon()
        icon1.addFile(u":/icon/door-slide-run-close.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_door_close.setIcon(icon1)
        self.obtn_door_close.setIconSize(QSize(65, 65))
        self.obtn_door_close.setFlat(False)

        self.horizontalLayout.addWidget(self.obtn_door_close)


        self.doorPanelHorizonLayout.addLayout(self.horizontalLayout)


        self.retranslateUi(DoorPanelHorizonWidget)

        self.obtn_door_open.setDefault(False)


        QMetaObject.connectSlotsByName(DoorPanelHorizonWidget)
    # setupUi

    def retranslateUi(self, DoorPanelHorizonWidget):
        DoorPanelHorizonWidget.setWindowTitle(QCoreApplication.translate("DoorPanelHorizonWidget", u"Form", None))
#if QT_CONFIG(tooltip)
        self.obtn_door_open.setToolTip(QCoreApplication.translate("DoorPanelHorizonWidget", u"Open Door", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_door_open.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_door_close.setToolTip(QCoreApplication.translate("DoorPanelHorizonWidget", u"Close Door", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_door_close.setText("")
    # retranslateUi

