# -*- coding: utf-8 -*-
# Auto-generated from header_a_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'header_a_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QSpacerItem, QWidget)
from src.ui import resources_rc

class Ui_HeaderWidget(object):
    def setupUi(self, HeaderWidget):
        if not HeaderWidget.objectName():
            HeaderWidget.setObjectName(u"HeaderWidget")
        HeaderWidget.resize(984, 80)
        HeaderWidget.setMinimumSize(QSize(984, 80))
        HeaderWidget.setMaximumSize(QSize(984, 80))
        font = QFont()
        font.setFamilies([u"Poppins"])
        HeaderWidget.setFont(font)
        HeaderWidget.setStyleSheet(u"QWidget#HeaderWidget {\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"* { font-family: 'Poppins', 'Noto Sans Thai'; }")
        self.headerLayout = QHBoxLayout(HeaderWidget)
        self.headerLayout.setObjectName(u"headerLayout")
        self.headerLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_left = QSpacerItem(230, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer_left)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer)

        self.olbl_title = QLabel(HeaderWidget)
        self.olbl_title.setObjectName(u"olbl_title")
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setPointSize(24)
        font1.setBold(True)
        self.olbl_title.setFont(font1)
        self.olbl_title.setStyleSheet(u"background-color: transparent; color: #000000; font-family: 'Poppins', 'Noto Sans Thai';")
        self.olbl_title.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.headerLayout.addWidget(self.olbl_title)

        self.horizontalSpacer_center = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer_center)

        self.ofrm_header_icons = QFrame(HeaderWidget)
        self.ofrm_header_icons.setObjectName(u"ofrm_header_icons")
        self.ofrm_header_icons.setMinimumSize(QSize(230, 80))
        self.ofrm_header_icons.setMaximumSize(QSize(230, 80))
        self.ofrm_header_icons.setStyleSheet(u"QFrame#ofrm_header_icons { background-color: transparent; }\n"
"\n"
"QPushButton {\n"
"	border: 5px solid #003057;\n"
"	border-radius: 35px;\n"
"	min-width: 60px;\n"
"	min-height: 60px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #e0e0e0;\n"
"}\n"
"\n"
"/* --- Status: Alert (Bell Only - Blinking support) --- */\n"
"QPushButton#obtn_alarm[status=\"alert_on\"] {\n"
"    background-color: rgba(243, 53, 53, 0.4);\n"
"    border: 5px solid #F33535;\n"
"}\n"
"QPushButton#obtn_alarm[status=\"alert_off\"] {\n"
"    background-color: transparent;\n"
"    border: 5px solid #003057;\n"
"}\n"
"\n"
"/* --- Status: Warning (General) --- */\n"
"QPushButton#obtn_alarm[status=\"warning\"] {\n"
"    background-color: rgba(255, 178, 0, 0.4);\n"
"    border: 5px solid #FFB200;\n"
"}")
        self.headerIconsLayout = QHBoxLayout(self.ofrm_header_icons)
        self.headerIconsLayout.setSpacing(10)
        self.headerIconsLayout.setObjectName(u"headerIconsLayout")
        self.headerIconsLayout.setContentsMargins(0, 0, 0, 0)
        self.obtn_warning = QPushButton(self.ofrm_header_icons)
        self.obtn_warning.setObjectName(u"obtn_warning")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obtn_warning.sizePolicy().hasHeightForWidth())
        self.obtn_warning.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/images/warning.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_warning.setIcon(icon)
        self.obtn_warning.setIconSize(QSize(55, 55))
        self.obtn_warning.setCheckable(False)

        self.headerIconsLayout.addWidget(self.obtn_warning)

        self.obtn_alarm = QPushButton(self.ofrm_header_icons)
        self.obtn_alarm.setObjectName(u"obtn_alarm")
        icon1 = QIcon()
        icon1.addFile(u":/icon/bell-blue-filled.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_alarm.setIcon(icon1)
        self.obtn_alarm.setIconSize(QSize(55, 55))
        self.obtn_alarm.setCheckable(False)

        self.headerIconsLayout.addWidget(self.obtn_alarm)

        self.obtn_lang = QPushButton(self.ofrm_header_icons)
        self.obtn_lang.setObjectName(u"obtn_lang")
        icon2 = QIcon()
        icon2.addFile(u":/images/th-TH.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/images/en-GB.png", QSize(), QIcon.Mode.Active, QIcon.State.On)
        icon2.addFile(u":/images/en-GB.png", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        self.obtn_lang.setIcon(icon2)
        self.obtn_lang.setIconSize(QSize(50, 50))
        self.obtn_lang.setCheckable(True)

        self.headerIconsLayout.addWidget(self.obtn_lang)


        self.headerLayout.addWidget(self.ofrm_header_icons)


        self.retranslateUi(HeaderWidget)

        QMetaObject.connectSlotsByName(HeaderWidget)
    # setupUi

    def retranslateUi(self, HeaderWidget):
        self.olbl_title.setText(QCoreApplication.translate("HeaderWidget", u"\u0e2b\u0e19\u0e49\u0e32\u0e2b\u0e25\u0e31\u0e01", None))
        self.obtn_warning.setText("")
        self.obtn_alarm.setText("")
        self.obtn_lang.setText("")
        pass
    # retranslateUi

