# -*- coding: utf-8 -*-
# Auto-generated from header_b_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'header_b_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QSpacerItem, QVBoxLayout,
    QWidget)
from src.ui import resources_rc

class Ui_HeaderBWidget(object):
    def setupUi(self, HeaderBWidget):
        if not HeaderBWidget.objectName():
            HeaderBWidget.setObjectName(u"HeaderBWidget")
        HeaderBWidget.resize(984, 80)
        HeaderBWidget.setMinimumSize(QSize(0, 80))
        HeaderBWidget.setMaximumSize(QSize(16777215, 80))
        font = QFont()
        font.setFamilies([u"Poppins"])
        HeaderBWidget.setFont(font)
        HeaderBWidget.setStyleSheet(u"background-color: transparent;\n"
"font-family: 'Poppins', 'Noto Sans Thai';")
        self.headerLayout = QHBoxLayout(HeaderBWidget)
        self.headerLayout.setSpacing(10)
        self.headerLayout.setObjectName(u"headerLayout")
        self.headerLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer = QSpacerItem(150, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer_2)

        self.olbl_title = QLabel(HeaderBWidget)
        self.olbl_title.setObjectName(u"olbl_title")
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setPointSize(24)
        font1.setBold(True)
        self.olbl_title.setFont(font1)
        self.olbl_title.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai';")
        self.olbl_title.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.headerLayout.addWidget(self.olbl_title)

        self.horizontalSpacer_center = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer_center)

        self.ofrm_header_icons = QFrame(HeaderBWidget)
        self.ofrm_header_icons.setObjectName(u"ofrm_header_icons")
        self.ofrm_header_icons.setStyleSheet(u"QPushButton {\n"
"    border: 5px solid #003057;\n"
"    border-radius: 35px;\n"
"    min-width: 60px;\n"
"    min-height: 60px;\n"
"    background-color: transparent;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0;\n"
"}")
        self.ofrm_header_icons.setFrameShape(QFrame.NoFrame)
        self.headerIconsLayout = QHBoxLayout(self.ofrm_header_icons)
        self.headerIconsLayout.setSpacing(10)
        self.headerIconsLayout.setObjectName(u"headerIconsLayout")
        self.headerIconsLayout.setContentsMargins(0, 0, 0, 0)
        self.ofrm_warning_placeholder = QFrame(self.ofrm_header_icons)
        self.ofrm_warning_placeholder.setObjectName(u"ofrm_warning_placeholder")
        self.ofrm_warning_placeholder.setMinimumSize(QSize(70, 70))
        self.ofrm_warning_placeholder.setMaximumSize(QSize(70, 70))
        self.ofrm_warning_placeholder.setFrameShape(QFrame.NoFrame)
        self.warningPlaceholderLayout = QVBoxLayout(self.ofrm_warning_placeholder)
        self.warningPlaceholderLayout.setSpacing(0)
        self.warningPlaceholderLayout.setObjectName(u"warningPlaceholderLayout")
        self.warningPlaceholderLayout.setContentsMargins(0, 0, 0, 0)
        self.obtn_warning = QPushButton(self.ofrm_warning_placeholder)
        self.obtn_warning.setObjectName(u"obtn_warning")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obtn_warning.sizePolicy().hasHeightForWidth())
        self.obtn_warning.setSizePolicy(sizePolicy)
        self.obtn_warning.setMinimumSize(QSize(70, 70))
        self.obtn_warning.setMaximumSize(QSize(70, 70))
        icon = QIcon()
        icon.addFile(u":/images/warning.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_warning.setIcon(icon)
        self.obtn_warning.setIconSize(QSize(55, 55))
        self.obtn_warning.setCheckable(False)

        self.warningPlaceholderLayout.addWidget(self.obtn_warning)


        self.headerIconsLayout.addWidget(self.ofrm_warning_placeholder)

        self.obtn_lang = QPushButton(self.ofrm_header_icons)
        self.obtn_lang.setObjectName(u"obtn_lang")
        sizePolicy.setHeightForWidth(self.obtn_lang.sizePolicy().hasHeightForWidth())
        self.obtn_lang.setSizePolicy(sizePolicy)
        self.obtn_lang.setMinimumSize(QSize(70, 70))
        self.obtn_lang.setMaximumSize(QSize(70, 70))
        icon1 = QIcon()
        icon1.addFile(u":/images/th-TH.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/images/en-GB.png", QSize(), QIcon.Mode.Active, QIcon.State.On)
        icon1.addFile(u":/images/en-GB.png", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        self.obtn_lang.setIcon(icon1)
        self.obtn_lang.setIconSize(QSize(50, 50))
        self.obtn_lang.setCheckable(True)

        self.headerIconsLayout.addWidget(self.obtn_lang)


        self.headerLayout.addWidget(self.ofrm_header_icons)


        self.retranslateUi(HeaderBWidget)

        QMetaObject.connectSlotsByName(HeaderBWidget)
    # setupUi

    def retranslateUi(self, HeaderBWidget):
        self.olbl_title.setText(QCoreApplication.translate("HeaderBWidget", u"Header Title", None))
#if QT_CONFIG(tooltip)
        self.obtn_warning.setToolTip(QCoreApplication.translate("HeaderBWidget", u"Warnings", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_warning.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_lang.setToolTip(QCoreApplication.translate("HeaderBWidget", u"Change Language", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_lang.setText("")
        pass
    # retranslateUi

