# -*- coding: utf-8 -*-
# Auto-generated from header_main_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'header_main_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLabel,
    QPushButton, QSizePolicy, QSpacerItem, QWidget)
from src.ui import resources_rc

class Ui_HeaderMainWidget(object):
    def setupUi(self, HeaderMainWidget):
        if not HeaderMainWidget.objectName():
            HeaderMainWidget.setObjectName(u"HeaderMainWidget")
        HeaderMainWidget.resize(884, 80)
        HeaderMainWidget.setMinimumSize(QSize(884, 80))
        HeaderMainWidget.setMaximumSize(QSize(884, 80))
        font = QFont()
        font.setFamilies([u"Poppins"])
        HeaderMainWidget.setFont(font)
        HeaderMainWidget.setStyleSheet(u"QFrame#HeaderMainWidget {\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"* { font-family: 'Poppins', 'Noto Sans Thai'; }")
        self.headerLayout = QHBoxLayout(HeaderMainWidget)
        self.headerLayout.setObjectName(u"headerLayout")
        self.headerLayout.setContentsMargins(0, 0, 20, 0)
        self.horizontalSpacer_left = QSpacerItem(250, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer_left)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer)

        self.olbl_title = QLabel(HeaderMainWidget)
        self.olbl_title.setObjectName(u"olbl_title")
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setPointSize(24)
        font1.setBold(True)
        self.olbl_title.setFont(font1)
        self.olbl_title.setStyleSheet(u"color: #000000; font-family: 'Poppins', 'Noto Sans Thai';")
        self.olbl_title.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.headerLayout.addWidget(self.olbl_title)

        self.horizontalSpacer_center = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.headerLayout.addItem(self.horizontalSpacer_center)

        self.ofrm_header_icons = QFrame(HeaderMainWidget)
        self.ofrm_header_icons.setObjectName(u"ofrm_header_icons")
        self.ofrm_header_icons.setMinimumSize(QSize(230, 80))
        self.ofrm_header_icons.setMaximumSize(QSize(230, 80))
        self.ofrm_header_icons.setStyleSheet(u"QPushButton {\n"
"	border: 5px solid #003057;\n"
"	border-radius: 35px;\n"
"	min-width: 60px;\n"
"	min-height: 60px;\n"
"}\n"
"QPushButton:pressed {\n"
"	background-color: #e0e0e0;\n"
"}")
        self.headerIconsLayout = QHBoxLayout(self.ofrm_header_icons)
        self.headerIconsLayout.setSpacing(10)
        self.headerIconsLayout.setObjectName(u"headerIconsLayout")
        self.headerIconsLayout.setContentsMargins(0, 0, 0, 0)
        self.obtn_warning_top = QPushButton(self.ofrm_header_icons)
        self.obtn_warning_top.setObjectName(u"obtn_warning_top")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obtn_warning_top.sizePolicy().hasHeightForWidth())
        self.obtn_warning_top.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u":/images/warning.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.obtn_warning_top.setIcon(icon)
        self.obtn_warning_top.setIconSize(QSize(55, 55))
        self.obtn_warning_top.setCheckable(False)

        self.headerIconsLayout.addWidget(self.obtn_warning_top)

        self.obtn_lang_top = QPushButton(self.ofrm_header_icons)
        self.obtn_lang_top.setObjectName(u"obtn_lang_top")
        icon1 = QIcon()
        icon1.addFile(u":/images/th-TH.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/images/en-GB.png", QSize(), QIcon.Mode.Active, QIcon.State.On)
        icon1.addFile(u":/images/en-GB.png", QSize(), QIcon.Mode.Selected, QIcon.State.On)
        self.obtn_lang_top.setIcon(icon1)
        self.obtn_lang_top.setIconSize(QSize(50, 50))
        self.obtn_lang_top.setCheckable(True)

        self.headerIconsLayout.addWidget(self.obtn_lang_top)

        self.obtn_login_logout_top = QPushButton(self.ofrm_header_icons)
        self.obtn_login_logout_top.setObjectName(u"obtn_login_logout_top")
        icon2 = QIcon()
        icon2.addFile(u":/images/login.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/icon/user-circle-filled.svg", QSize(), QIcon.Mode.Normal, QIcon.State.On)
        self.obtn_login_logout_top.setIcon(icon2)
        self.obtn_login_logout_top.setIconSize(QSize(55, 55))
        self.obtn_login_logout_top.setCheckable(False)

        self.headerIconsLayout.addWidget(self.obtn_login_logout_top)


        self.headerLayout.addWidget(self.ofrm_header_icons)


        self.retranslateUi(HeaderMainWidget)

        QMetaObject.connectSlotsByName(HeaderMainWidget)
    # setupUi

    def retranslateUi(self, HeaderMainWidget):
        self.olbl_title.setText(QCoreApplication.translate("HeaderMainWidget", u"\u0e2b\u0e19\u0e49\u0e32\u0e2b\u0e25\u0e31\u0e01", None))
        self.obtn_warning_top.setText("")
        self.obtn_lang_top.setText("")
        self.obtn_login_logout_top.setText("")
        pass
    # retranslateUi

