# -*- coding: utf-8 -*-
# Auto-generated from sidebar_menu_widget.ui
# DO NOT EDIT THIS FILE MANUALLY!
# Regenerate using: python scripts/compile_ui.py

# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sidebar_menu_widget.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QPushButton, QSizePolicy,
    QVBoxLayout, QWidget)
from src.ui import resources_rc

class Ui_SidebarMenuWidget(object):
    def setupUi(self, SidebarMenuWidget):
        if not SidebarMenuWidget.objectName():
            SidebarMenuWidget.setObjectName(u"SidebarMenuWidget")
        SidebarMenuWidget.resize(140, 600)
        SidebarMenuWidget.setMinimumSize(QSize(140, 600))
        SidebarMenuWidget.setMaximumSize(QSize(140, 600))
        font = QFont()
        font.setFamilies([u"Poppins"])
        font.setKerning(True)
        SidebarMenuWidget.setFont(font)
        SidebarMenuWidget.setStyleSheet(u"/* \n"
"DESIGN LOGIC: SIDEBAR MENU ANIMATION\n"
"- ofrm_selection_indicator: A floating QFrame used as an animated selection background.\n"
"- Logic: In Python, use QPropertyAnimation on 'geometry' property to move this frame.\n"
"- Animation: Target the geometry of the clicked QPushButton.\n"
"- Styling: QPushButton:checked is transparent to reveal this indicator behind it.\n"
"- Blinking: Use status='alert_on'/'alert_off' with a QTimer for the bell icon.\n"
"*/\n"
"\n"
"SidebarMenuWidget, QWidget#SidebarMenuWidget, QWidget#sidebar_menu_widget {\n"
"	background-color: #FFFFFF;\n"
"	border-top-right-radius: 70px;\n"
"	border-bottom-right-radius: 70px;\n"
"	border: 7px solid #003057;\n"
"}\n"
"QPushButton {\n"
"	background-color: transparent;\n"
"	border: none;\n"
"	color: white;\n"
"    padding: 10px;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"	background-color: rgba(255, 255, 255, 0.2);\n"
"}\n"
"QPushButton:checked {\n"
"	background-color: transparent;\n"
"}\n"
"\n"
"QFrame#ofrm_selection"
                        "_indicator {\n"
"	background-color: rgba(255, 255, 255, 0.3);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"/* --- Status: Alert (Bell Only - Blinking support) --- */\n"
"/* Icon is managed by Python setIcon() \u2014 no qproperty-icon here */\n"
"QPushButton#obtn_alarm_side[status=\"alert\"],\n"
"QPushButton#obtn_alarm_side[status=\"alert_on\"],\n"
"QPushButton#obtn_alarm_side[status=\"alert_off\"] {\n"
"    background-color: rgba(243, 53, 53, 0.0);\n"
"    border: none;\n"
"}\n"
"QPushButton#obtn_alarm_side[status=\"alert\"]:hover,\n"
"QPushButton#obtn_alarm_side[status=\"alert_on\"]:hover,\n"
"QPushButton#obtn_alarm_side[status=\"alert_off\"]:hover {\n"
"    background-color: rgba(243, 53, 53, 0);\n"
"}\n"
"\n"
"/* --- Status: Warning (General) --- */\n"
"QPushButton[status=\"warning\"] {\n"
"    background-color: rgba(255, 178, 0, 0.4);\n"
"    border: 2px solid #FFB200;\n"
"}\n"
"QPushButton[status=\"warning\"]:hover {\n"
"    background-color: rgba(255, 178, 0, 0.6);\n"
"}\n"
"\n"
"* { font-family: 'Poppins"
                        "', 'Noto Sans Thai'; }")
        SidebarMenuWidget.setProperty(u"lineWidth", -2)
        self.verticalLayout = QVBoxLayout(SidebarMenuWidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.ofrm_sidebar_bg = QFrame(SidebarMenuWidget)
        self.ofrm_sidebar_bg.setObjectName(u"ofrm_sidebar_bg")
        self.ofrm_sidebar_bg.setEnabled(True)
        self.ofrm_sidebar_bg.setMinimumSize(QSize(90, 550))
        self.ofrm_sidebar_bg.setMaximumSize(QSize(90, 550))
        self.ofrm_sidebar_bg.setStyleSheet(u"QFrame {\n"
"	background-color: #003057;\n"
"	border-radius: 45px;\n"
"}")
        self.ofrm_sidebar_bg.setFrameShape(QFrame.StyledPanel)
        self.ofrm_sidebar_bg.setFrameShadow(QFrame.Raised)
        self.ofrm_selection_indicator = QFrame(self.ofrm_sidebar_bg)
        self.ofrm_selection_indicator.setObjectName(u"ofrm_selection_indicator")
        self.ofrm_selection_indicator.setGeometry(QRect(15, 35, 60, 60))
        self.ofrm_selection_indicator.setStyleSheet(u"")
        self.ofrm_selection_indicator.setFrameShape(QFrame.StyledPanel)
        self.ofrm_selection_indicator.setFrameShadow(QFrame.Raised)
        self.verticalLayout_Inbox = QVBoxLayout(self.ofrm_sidebar_bg)
        self.verticalLayout_Inbox.setSpacing(10)
        self.verticalLayout_Inbox.setObjectName(u"verticalLayout_Inbox")
        self.verticalLayout_Inbox.setContentsMargins(0, 35, 0, 35)
        self.obtn_home_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_home_side.setObjectName(u"obtn_home_side")
        self.obtn_home_side.setMinimumSize(QSize(60, 60))
        self.obtn_home_side.setMaximumSize(QSize(60, 60))
        icon = QIcon()
        icon.addFile(u":/icon/home-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon.addFile(u":/icon/home-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_home_side.setIcon(icon)
        self.obtn_home_side.setIconSize(QSize(55, 55))
        self.obtn_home_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_home_side, 0, Qt.AlignHCenter)

        self.obtn_testing_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_testing_side.setObjectName(u"obtn_testing_side")
        self.obtn_testing_side.setMinimumSize(QSize(60, 60))
        self.obtn_testing_side.setMaximumSize(QSize(60, 60))
        icon1 = QIcon()
        icon1.addFile(u":/icon/adjustments-vertical-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon1.addFile(u":/icon/adjustments-vertical-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_testing_side.setIcon(icon1)
        self.obtn_testing_side.setIconSize(QSize(55, 55))
        self.obtn_testing_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_testing_side, 0, Qt.AlignHCenter)

        self.obtn_users_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_users_side.setObjectName(u"obtn_users_side")
        self.obtn_users_side.setMinimumSize(QSize(60, 60))
        self.obtn_users_side.setMaximumSize(QSize(60, 60))
        icon2 = QIcon()
        icon2.addFile(u":/icon/users-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon2.addFile(u":/icon/users-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_users_side.setIcon(icon2)
        self.obtn_users_side.setIconSize(QSize(55, 55))
        self.obtn_users_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_users_side, 0, Qt.AlignHCenter)

        self.obtn_history_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_history_side.setObjectName(u"obtn_history_side")
        self.obtn_history_side.setMinimumSize(QSize(60, 60))
        self.obtn_history_side.setMaximumSize(QSize(60, 60))
        icon3 = QIcon()
        icon3.addFile(u":/icon/newspaper-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon3.addFile(u":/icon/newspaper-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_history_side.setIcon(icon3)
        self.obtn_history_side.setIconSize(QSize(55, 55))
        self.obtn_history_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_history_side, 0, Qt.AlignHCenter)

        self.obtn_alarm_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_alarm_side.setObjectName(u"obtn_alarm_side")
        self.obtn_alarm_side.setMinimumSize(QSize(60, 60))
        self.obtn_alarm_side.setMaximumSize(QSize(60, 60))
        icon4 = QIcon()
        icon4.addFile(u":/icon/bell-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon4.addFile(u":/icon/bell-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_alarm_side.setIcon(icon4)
        self.obtn_alarm_side.setIconSize(QSize(55, 55))
        self.obtn_alarm_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_alarm_side, 0, Qt.AlignHCenter)

        self.obtn_setting_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_setting_side.setObjectName(u"obtn_setting_side")
        self.obtn_setting_side.setMinimumSize(QSize(60, 60))
        self.obtn_setting_side.setMaximumSize(QSize(60, 60))
        icon5 = QIcon()
        icon5.addFile(u":/icon/cog-6-tooth-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon5.addFile(u":/icon/cog-6-tooth-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_setting_side.setIcon(icon5)
        self.obtn_setting_side.setIconSize(QSize(55, 55))
        self.obtn_setting_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_setting_side, 0, Qt.AlignHCenter)

        self.obtn_maintenance_side = QPushButton(self.ofrm_sidebar_bg)
        self.obtn_maintenance_side.setObjectName(u"obtn_maintenance_side")
        self.obtn_maintenance_side.setMinimumSize(QSize(60, 60))
        self.obtn_maintenance_side.setMaximumSize(QSize(60, 60))
        icon6 = QIcon()
        icon6.addFile(u":/icon/wrench-screwdriver-outline.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        icon6.addFile(u":/icon/wrench-screwdriver-filled.svg", QSize(), QIcon.Mode.Active, QIcon.State.On)
        self.obtn_maintenance_side.setIcon(icon6)
        self.obtn_maintenance_side.setIconSize(QSize(50, 50))
        self.obtn_maintenance_side.setCheckable(True)

        self.verticalLayout_Inbox.addWidget(self.obtn_maintenance_side, 0, Qt.AlignHCenter)


        self.verticalLayout.addWidget(self.ofrm_sidebar_bg, 0, Qt.AlignHCenter|Qt.AlignVCenter)


        self.retranslateUi(SidebarMenuWidget)

        QMetaObject.connectSlotsByName(SidebarMenuWidget)
    # setupUi

    def retranslateUi(self, SidebarMenuWidget):
#if QT_CONFIG(tooltip)
        self.obtn_home_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"Home", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_home_side.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_testing_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"Testing Program", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_testing_side.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_users_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"Users/RFID", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_users_side.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_history_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"History", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_history_side.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_alarm_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"Alarm", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_alarm_side.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_setting_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_setting_side.setText("")
#if QT_CONFIG(tooltip)
        self.obtn_maintenance_side.setToolTip(QCoreApplication.translate("SidebarMenuWidget", u"Maintenance", None))
#endif // QT_CONFIG(tooltip)
        self.obtn_maintenance_side.setText("")
        pass
    # retranslateUi

